version: '3.8'
services:
  mongodb:
    image: mongodb/mongodb-community-server:8.0-ubuntu2204
    user: root
    command: mongod --noauth --bind_ip_all
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: