version: '3.8'
services:
  mongodb:
    image: mongodb/mongodb-community-server:8.0-ubuntu2204
    user: root
    command: mongod --noauth --bind_ip_all
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

volumes:
  mongodb_data:
  redis_data: