version: '3.8'
services:
  mongodb:
    image: mongodb/mongodb-community-server:8.0-ubuntu2204
    user: root
    command: mongod --noauth --bind_ip_all --port 27018
    ports:
      - "27018:27018"
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:7-alpine
    ports:
      - "6380:6380"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --requirepass defaultpassword123

volumes:
  mongodb_data:
  redis_data: