import { NextRequest, NextResponse } from "next/server";
import { auth } from "@/src/lib/auth";
import { isUserInSpace } from "@/src/dao/userDao";
import { getSpaceById } from "@/src/dao/spaceDao";
import { ISpace } from "@/src/types/space";
import { nanoid } from "nanoid";
import { extractAvatarIdentityFromPrompt, improveAvatarPrompt } from "@/src/lib/workflowai";
import { generateAvatarImageComfySrpo, generateAvatarImageFluxSrpo } from "@/src/lib/fal";

// Common hint used to bias generations for podcast scenes
const PODCAST_HINT = " The scene is a podcast, the avatar is not looking at the camera, he is looking away as if he were talking, there is a microphone in front of him.";

export async function GET(
  req: NextRequest,
  { params }: { params: { id: string } }
) {
  const session = await auth();

  if (!session || !session.user || !session.user.id) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  console.log("GET /api/space/id/avatars by user: ", session.user.id);

  try {
    const userIsInSpace: boolean = await isUserInSpace(
      session.user.id,
      params.id
    );

    if (!userIsInSpace) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    const space: ISpace = await getSpaceById(params.id);

    if (!space) {
      return NextResponse.json({ error: "Space not found" }, { status: 404 });
    }

    // Preserve custom avatar ids generated by nanoid without reformatting the rest
    const rawAvatars: any[] = (space as any).avatars || [];
    const avatarsWithFixedIds = rawAvatars.map((a: any) => {
      const base = typeof a.toObject === 'function' ? a.toObject() : a;
      return {
        ...base,
        id: a.id, // préserver l'id custom d'avatar
      }
    });

    return NextResponse.json({ data: avatarsWithFixedIds });
  } catch (error) {
    console.error("Error getting space avatars:", error);
    return NextResponse.json(
      { error: "Error getting space avatars" },
      { status: 500 }
    );
  }
}

export async function POST(
  req: NextRequest,
  { params }: { params: { id: string } }
) {
  const session = await auth();

  if (!session || !session.user || !session.user.id) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  try {
    const userIsInSpace: boolean = await isUserInSpace(
      session.user.id,
      params.id
    );
    if (!userIsInSpace) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    const space: ISpace = await getSpaceById(params.id);
    if (!space) {
      return NextResponse.json({ error: "Space not found" }, { status: 404 });
    }

    // Enforce avatar creation limit (space-level)
    const currentCount = ((space as any).avatarsCreatedCount as number) || 0;
    const limit = ((space as any).avatarsLimit as number) ?? 5;
    if (currentCount >= limit) {
      return NextResponse.json({ error: "Avatar limit reached" }, { status: 403 });
    }

    const body = await req.json().catch(() => ({}));
    const basePrompt: string | undefined = body?.prompt;
    const style: 'ugc-realist' | 'studio' | 'podcast' | undefined = body?.style;
    const format: 'vertical' | 'horizontal' | 'square' | 'ads' | undefined = body?.format;
    const imageUrl: string | undefined = body?.imageUrl;
    const imageUrls: string[] = Array.isArray(body?.imageUrls)
      ? (body.imageUrls as string[]).filter((u) => typeof u === "string" && u.length > 0)
      : [];
    // Backward compatibility: allow single imageUrl or array imageUrls
    const providedImageUrls: string[] = [
      ...imageUrls,
      ...(typeof imageUrl === "string" && imageUrl.length > 0 ? [imageUrl] : []),
    ];
    if (!basePrompt && providedImageUrls.length === 0) {
      return NextResponse.json(
        { error: "prompt or imageUrl(s) is required" },
        { status: 400 }
      );
    }

    // 1) Extract identity from prompt when provided
    let inferredName: string | undefined;
    let inferredGender: "male" | "female" | undefined;
    let inferredAge: string | undefined;
    let inferredTags: string[] | undefined;
    let inferredPlace: string | undefined;
    if (basePrompt) {
      const extracted = await extractAvatarIdentityFromPrompt(basePrompt);
      inferredName = extracted.name;
      inferredGender = extracted.gender;
      inferredAge = extracted.age;
      inferredTags = extracted.tags;
      inferredPlace = extracted.place;
    }

    const name: string = inferredName || "Custom Avatar";
    const gender: "male" | "female" = (inferredGender || "male") as any;
    const age: string = inferredAge || "undefined";
    const tags: string[] = Array.isArray(inferredTags) ? inferredTags : [];
    const place: string = inferredPlace || "unspecified";

    const avatarId = nanoid();

    // 2) Auto-create looks
    // If images are provided: one look per image; else: create an empty look to be filled by background generation
    let finalPrompt: string | undefined = undefined;
    if (providedImageUrls.length === 0 && basePrompt) {
      // Inject podcast hint before enhancement to influence the improved prompt
      const sourcePrompt = style === 'podcast' ? `${basePrompt}${PODCAST_HINT}` : basePrompt;
      const improved = await improveAvatarPrompt(sourcePrompt).catch(() => ({ enhancedPrompt: sourcePrompt }));
      finalPrompt = improved.enhancedPrompt || sourcePrompt;
    }

    const looks = (providedImageUrls.length > 0)
      ? providedImageUrls.map((url: string, idx: number) => ({
          id: nanoid(),
          name: `Look ${idx + 1}`,
          place: place,
          tags: tags,
          thumbnail: url,
          previewUrl: "",
          videoUrl: "",
          format: "vertical",
          settings: {},
        }))
      : [{
          id: nanoid(),
          name: "First Look",
          place: place,
          tags: tags,
          thumbnail: "",
          previewUrl: "",
          videoUrl: "",
          format: "vertical",
          settings: {},
        }];

    const newAvatar: any = {
      id: avatarId,
      name,
      age,
      gender,
      tags,
      thumbnail: providedImageUrls[0] || "",
      looks: looks,
    };

    (space as any).avatars.push(newAvatar);
    (space as any).avatarsCreatedCount = currentCount + 1;
    await (space as any).save();

    // Background image generation only when no image was provided
    if (providedImageUrls.length === 0 && finalPrompt) {
      Promise.resolve()
        .then(async () => {
          try {
            const imageSize = format === 'horizontal' ? 'landscape_16_9' : (format === 'vertical' ? 'portrait_16_9' : undefined);
            const img = style === 'ugc-realist'
              ? await generateAvatarImageComfySrpo({ prompt: finalPrompt as string })
              : await generateAvatarImageFluxSrpo({ prompt: finalPrompt as string, image_size: imageSize });
            const refreshedSpace: ISpace = await getSpaceById(params.id);
            const avatarRef: any = (refreshedSpace as any).avatars.find((a: any) => a.id === avatarId);
            // Update the first look only when none were provided initially
            const firstLook: any = avatarRef?.looks?.[0];
            if (firstLook && !firstLook.thumbnail) firstLook.thumbnail = img.url;
            if (avatarRef && !avatarRef.thumbnail) {
              avatarRef.thumbnail = img.url;
            }
            await (refreshedSpace as any).save();
          } catch (e) {
            console.error('Error generating first avatar look image (background)', e);
          }
        })
        .catch(() => {});
    }

    return NextResponse.json({ data: newAvatar }, { status: 201 });
  } catch (error) {
    console.error("Error creating space avatar:", error);
    return NextResponse.json(
      { error: "Error creating space avatar" },
      { status: 500 }
    );
  }
}
