export enum Steps {
  MEDIA_UPLOAD = "MEDIA_UPLOAD",
  QUEUE = "QUEUE",
  VOICE_GENERATION = "VOICE_GENERATION",
  TRANSCRIPTION = "TRANSCRIPTION",
  SEARCH_MEDIA = "SEARCH_MEDIA",
  ANALYZE_FOUND_MEDIA = "ANALYZE_FOUND_MEDIA",
  ANALYZE_YOUR_MEDIA = "ANALYZE_YOUR_MEDIA",
  PLACE_BROLL = "PLACE_BROLL",
  DISPLAY_BROLL = "DISPLAY_BROLL",
  REDIRECTING = "REDIRECTING",
  SEARCH_GOOGLE_IMAGES = "SEARCH_GOOGLE_IMAGES",
}

export enum StepState {
  PENDING = "PENDING",
  IN_PROGRESS = "IN_PROGRESS",
  COMPLETED = "COMPLETED",
  FAILED = "FAILED"
}

export interface Step {
  id: number;
  name: Steps;
  state: StepState;
  progress: number;
}