export enum Steps {
  MEDIA_UPLOAD = "MEDIA_UPLOAD",
  VOICE_GENERATION = "VOICE_GENERATION",
  TRANSCRIPTION = "TRANSCRIPTION",
  AVATAR_GENERATION = "AVATAR_GENERATION",
  SEARCH_MEDIA = "SEARCH_MEDIA",
  ANALYZE_YOUR_MEDIA = "ANALYZE_YOUR_MEDIA",
  ANALYZE_NEW_MEDIA = "ANALYZE_NEW_MEDIA",
}

export enum StepState {
  PENDING = "PENDING",
  IN_PROGRESS = "IN_PROGRESS",
  COMPLETED = "COMPLETED",
  FAILED = "FAILED"
}

export interface Step {
  id: number;
  name: Steps;
  state: StepState;
  progress: number;
}