import { ITransition } from "../types/video"

export const transitions : ITransition[] = [
    {
        durationInFrames: 98,
        video: "https://assets.hoox.video/Film%20Burn%20Red%20Burn.mp4",
        thumbnail: "https://assets.hoox.video/film-burn-red-thumbnail.png",
        fullAt: 14,
        category: "film-burn",
    },
    {
        durationInFrames: 30,
        video: "https://assets.hoox.video/Transition%20verte.mp4",
        thumbnail: "https://assets.hoox.video/transition-vert-thumbnail.png",
        fullAt: 17,
        category: "click",
    },
    {
        durationInFrames: 60,
        video: "https://assets.hoox.video/1%20Analog%20VHS.mp4",
        thumbnail: "https://assets.hoox.video/1%20Analog%20VHS-thumbnail.png",
        fullAt: 30,
        category: "Analog VHS",
    },
    {
        durationInFrames: 60,
        video: "https://assets.hoox.video/13%20Flares.mp4",
        thumbnail: "https://assets.hoox.video/13%20Flares-thumbnail.png",
        fullAt: 30,
        category: "Flares",
    },
    {
        durationInFrames: 60,
        video: "https://assets.hoox.video/14%20Flares.mp4",
        thumbnail: "https://assets.hoox.video/14%20Flares-thumbnail.png",
        fullAt: 30,
        category: "Flares",
    },
    {
        durationInFrames: 60,
        video: "https://assets.hoox.video/15%20Flares.mp4",
        thumbnail: "https://assets.hoox.video/15%20Flares-thumbnail.png",
        fullAt: 30,
        category: "Flares",
    },
    {
        durationInFrames: 60,
        video: "https://assets.hoox.video/19%20Flares.mp4",
        thumbnail: "https://assets.hoox.video/19%20Flares-thumbnail.png",
        fullAt: 30,
        category: "Flares",
    },
    {
        durationInFrames: 45,
        video: "https://assets.hoox.video/2%20Analog%20VHS.mp4",
        thumbnail: "https://assets.hoox.video/2%20Analog%20VHS-thumbnail.png",
        fullAt: 22,
        category: "Analog VHS",
    },
    {
        durationInFrames: 60,
        video: "https://assets.hoox.video/20%20Flares.mp4",
        thumbnail: "https://assets.hoox.video/20%20Flares-thumbnail.png",
        fullAt: 30,
        category: "Flares",
    },
    {
        durationInFrames: 60,
        video: "https://assets.hoox.video/21%20Dynamic%20Light.mp4",
        thumbnail: "https://assets.hoox.video/21%20Dynamic%20Light-thumbnail.png",
        fullAt: 30,
        category: "Dynamic Light",
    },
    {
        durationInFrames: 60,
        video: "https://assets.hoox.video/25%20Dynamic%20Light.mp4",
        thumbnail: "https://assets.hoox.video/25%20Dynamic%20Light-thumbnail.png",
        fullAt: 30,
        category: "Dynamic Light",
    },
    {
        durationInFrames: 60,
        video: "https://assets.hoox.video/26%20Dynamic%20Light.mp4",
        thumbnail: "https://assets.hoox.video/26%20Dynamic%20Light-thumbnail.png",
        fullAt: 30,
        category: "Dynamic Light",
    },
    {
        durationInFrames: 60,
        video: "https://assets.hoox.video/27%20Dynamic%20Light.mp4",
        thumbnail: "https://assets.hoox.video/27%20Dynamic%20Light-thumbnail.png",
        fullAt: 30,
        category: "Dynamic Light",
    },
    {
        durationInFrames: 60,
        video: "https://assets.hoox.video/3%20Analog%20VHS.mp4",
        thumbnail: "https://assets.hoox.video/3%20Analog%20VHS-thumbnail.png",
        fullAt: 30,
        category: "Analog VHS",
    },
    {
        durationInFrames: 60,
        video: "https://assets.hoox.video/31%20Burnt%20Film.mp4",
        thumbnail: "https://assets.hoox.video/31%20Burnt%20Film-thumbnail.png",
        fullAt: 30,
        category: "Burnt Film",
    },
    {
        durationInFrames: 60,
        video: "https://assets.hoox.video/32%20Burnt%20Film.mp4",
        thumbnail: "https://assets.hoox.video/32%20Burnt%20Film-thumbnail.png",
        fullAt: 30,
        category: "Burnt Film",
    },
    {
        durationInFrames: 30,
        video: "https://assets.hoox.video/33%20Burnt%20Film.mp4",
        thumbnail: "https://assets.hoox.video/33%20Burnt%20Film-thumbnail.png",
        fullAt: 15,
        category: "Burnt Film",
    },
    {
        durationInFrames: 60,
        video: "https://assets.hoox.video/37%20Burnt%20Film.mp4",
        thumbnail: "https://assets.hoox.video/37%20Burnt%20Film-thumbnail.png",
        fullAt: 30,
        category: "Burnt Film",
    },
    {
        durationInFrames: 60,
        video: "https://assets.hoox.video/38%20Burnt%20Film.mp4",
        thumbnail: "https://assets.hoox.video/38%20Burnt%20Film-thumbnail.png",
        fullAt: 30,
        category: "Burnt Film",
    },
    {
        durationInFrames: 60,
        video: "https://assets.hoox.video/39%20Burnt%20Film.mp4",
        thumbnail: "https://assets.hoox.video/39%20Burnt%20Film-thumbnail.png",
        fullAt: 30,
        category: "Burnt Film",
    },
    {
        durationInFrames: 60,
        video: "https://assets.hoox.video/43%20Neon%20Glitch.mp4",
        thumbnail: "https://assets.hoox.video/43%20Neon%20Glitch-thumbnail.png",
        fullAt: 30,
        category: "Neon Glitch",
    },
    {
        durationInFrames: 60,
        video: "https://assets.hoox.video/44%20Neon%20Glitch.mp4",
        thumbnail: "https://assets.hoox.video/44%20Neon%20Glitch-thumbnail.png",
        fullAt: 30,
        category: "Neon Glitch",
    },
    {
        durationInFrames: 75,
        video: "https://assets.hoox.video/45%20Neon%20Glitch.mp4",
        thumbnail: "https://assets.hoox.video/45%20Neon%20Glitch-thumbnail.png",
        fullAt: 37,
        category: "Neon Glitch",
    },
    {
        durationInFrames: 45,
        video: "https://assets.hoox.video/49%20Neon%20Glitch.mp4",
        thumbnail: "https://assets.hoox.video/49%20Neon%20Glitch-thumbnail.png",
        fullAt: 22,
        category: "Neon Glitch",
    },
    {
        durationInFrames: 60,
        video: "https://assets.hoox.video/50%20Neon%20Glitch.mp4",
        thumbnail: "https://assets.hoox.video/50%20Neon%20Glitch-thumbnail.png",
        fullAt: 30,
        category: "Neon Glitch",
    },
    {
        durationInFrames: 75,
        video: "https://assets.hoox.video/51%20Retro%20Slide.mp4",
        thumbnail: "https://assets.hoox.video/51%20Retro%20Slide-thumbnail.png",
        fullAt: 37,
        category: "Retro Slide",
    },
    {
        durationInFrames: 60,
        video: "https://assets.hoox.video/55%20Retro%20Slide.mp4",
        thumbnail: "https://assets.hoox.video/55%20Retro%20Slide-thumbnail.png",
        fullAt: 30,
        category: "Retro Slide",
    },
    {
        durationInFrames: 60,
        video: "https://assets.hoox.video/56%20Retro%20Slide.mp4",
        thumbnail: "https://assets.hoox.video/56%20Retro%20Slide-thumbnail.png",
        fullAt: 30,
        category: "Retro Slide",
    },
    {
        durationInFrames: 60,
        video: "https://assets.hoox.video/57%20Retro%20Slide.mp4",
        thumbnail: "https://assets.hoox.video/57%20Retro%20Slide-thumbnail.png",
        fullAt: 30,
        category: "Retro Slide",
    },
    {
        durationInFrames: 75,
        video: "https://assets.hoox.video/61%20Vintage%20Film.mp4",
        thumbnail: "https://assets.hoox.video/61%20Vintage%20Film-thumbnail.png",
        fullAt: 37,
        category: "Vintage Film",
    },
    {
        durationInFrames: 45,
        video: "https://assets.hoox.video/62%20Vintage%20Film.mp4",
        thumbnail: "https://assets.hoox.video/62%20Vintage%20Film-thumbnail.png",
        fullAt: 22,
        category: "Vintage Film",
    },
    {
        durationInFrames: 60,
        video: "https://assets.hoox.video/63%20Vintage%20Film.mp4",
        thumbnail: "https://assets.hoox.video/63%20Vintage%20Film-thumbnail.png",
        fullAt: 30,
        category: "Vintage Film",
    },
    {
        durationInFrames: 60,
        video: "https://assets.hoox.video/67%20Vintage%20Film.mp4",
        thumbnail: "https://assets.hoox.video/67%20Vintage%20Film-thumbnail.png",
        fullAt: 30,
        category: "Vintage Film",
    },
    {
        durationInFrames: 45,
        video: "https://assets.hoox.video/68%20Vintage%20Film.mp4",
        thumbnail: "https://assets.hoox.video/68%20Vintage%20Film-thumbnail.png",
        fullAt: 22,
        category: "Vintage Film",
    },
    {
        durationInFrames: 75,
        video: "https://assets.hoox.video/69%20Vintage%20Film.mp4",
        thumbnail: "https://assets.hoox.video/69%20Vintage%20Film-thumbnail.png",
        fullAt: 37,
        category: "Vintage Film",
    },
    {
        durationInFrames: 60,
        video: "https://assets.hoox.video/7%20Analog%20VHS.mp4",
        thumbnail: "https://assets.hoox.video/7%20Analog%20VHS-thumbnail.png",
        fullAt: 30,
        category: "Analog VHS",
    },
    {
        durationInFrames: 75,
        video: "https://assets.hoox.video/73%20X-Ray.mp4",
        thumbnail: "https://assets.hoox.video/73%20X-Ray-thumbnail.png",
        fullAt: 37,
        category: "X-Ray",
    },
    {
        durationInFrames: 75,
        video: "https://assets.hoox.video/74%20X-Ray.mp4",
        thumbnail: "https://assets.hoox.video/74%20X-Ray-thumbnail.png",
        fullAt: 37,
        category: "X-Ray",
    },
    {
        durationInFrames: 45,
        video: "https://assets.hoox.video/75%20X-Ray.mp4",
        thumbnail: "https://assets.hoox.video/75%20X-Ray-thumbnail.png",
        fullAt: 22,
        category: "X-Ray",
    },
    {
        durationInFrames: 45,
        video: "https://assets.hoox.video/79%20X-Ray.mp4",
        thumbnail: "https://assets.hoox.video/79%20X-Ray-thumbnail.png",
        fullAt: 22,
        category: "X-Ray",
    },
    {
        durationInFrames: 60,
        video: "https://assets.hoox.video/8%20Analog%20VHS.mp4",
        thumbnail: "https://assets.hoox.video/8%20Analog%20VHS-thumbnail.png",
        fullAt: 30,
        category: "Analog VHS",
    },
    {
        durationInFrames: 30,
        video: "https://assets.hoox.video/80%20X-Ray.mp4",
        thumbnail: "https://assets.hoox.video/80%20X-Ray-thumbnail.png",
        fullAt: 15,
        category: "X-Ray",
    },
    {
        durationInFrames: 75,
        video: "https://assets.hoox.video/81%20Signal.mp4",
        thumbnail: "https://assets.hoox.video/81%20Signal-thumbnail.png",
        fullAt: 37,
        category: "Signal",
    },
    {
        durationInFrames: 45,
        video: "https://assets.hoox.video/85%20Signal.mp4",
        thumbnail: "https://assets.hoox.video/85%20Signal-thumbnail.png",
        fullAt: 22,
        category: "Signal",
    },
    {
        durationInFrames: 45,
        video: "https://assets.hoox.video/86%20Signal.mp4",
        thumbnail: "https://assets.hoox.video/86%20Signal-thumbnail.png",
        fullAt: 22,
        category: "Signal",
    },
    {
        durationInFrames: 60,
        video: "https://assets.hoox.video/87%20Signal.mp4",
        thumbnail: "https://assets.hoox.video/87%20Signal-thumbnail.png",
        fullAt: 30,
        category: "Signal",
    },
    {
        durationInFrames: 60,
        video: "https://assets.hoox.video/9%20Analog%20VHS.mp4",
        thumbnail: "https://assets.hoox.video/9%20Analog%20VHS-thumbnail.png",
        fullAt: 30,
        category: "Analog VHS",
    },
    {
        durationInFrames: 60,
        video: "https://assets.hoox.video/91%20Old%20Film.mp4",
        thumbnail: "https://assets.hoox.video/91%20Old%20Film-thumbnail.png",
        fullAt: 30,
        category: "Old Film",
    },
    {
        durationInFrames: 60,
        video: "https://assets.hoox.video/92%20Old%20Film.mp4",
        thumbnail: "https://assets.hoox.video/92%20Old%20Film-thumbnail.png",
        fullAt: 30,
        category: "Old Film",
    },
    {
        durationInFrames: 75,
        video: "https://assets.hoox.video/93%20Old%20Film.mp4",
        thumbnail: "https://assets.hoox.video/93%20Old%20Film-thumbnail.png",
        fullAt: 37,
        category: "Old Film",
    },
    {
        durationInFrames: 60,
        video: "https://assets.hoox.video/97%20Old%20Film.mp4",
        thumbnail: "https://assets.hoox.video/97%20Old%20Film-thumbnail.png",
        fullAt: 30,
        category: "Old Film",
    },
    {
        durationInFrames: 30,
        video: "https://assets.hoox.video/98%20Old%20Film.mp4",
        thumbnail: "https://assets.hoox.video/98%20Old%20Film-thumbnail.png",
        fullAt: 15,
        category: "Old Film",
    },
    {
        durationInFrames: 60,
        video: "https://assets.hoox.video/99%20Old%20Film.mp4",
        thumbnail: "https://assets.hoox.video/99%20Old%20Film-thumbnail.png",
        fullAt: 30,
        category: "Old Film",
    }
]

export const sounds = [
    {
        name: "Burn Fizzle",
        url: "https://assets.hoox.video/Film%20Burn%20Fizzle.wav",
        category: "film-burn",
        soundPeakAt: 0
    },
    {
        name: "Click 1",
        url: "https://assets.hoox.video/Clicks.mp3",
        category: "click",
        soundPeakAt: 26
    }
]