import { PlanName } from '../types/enums'
import { Voice } from '../types/voice'

export const voicesConfig: Voice[] = [
  {
    id: 'English_expressive_narrator',
    name: 'James',
    language: 'english',
    accent: 'american',
    gender: 'male',
    age: 'middle aged',
    tags: ['narration', 'storytelling'],
    plan: PlanName.FREE,
    previewUrl: 'https://media.hoox.video/d51c0640-4693-40a3-9133-9f7aa48f82c1.mp3',
    mode: 'minimax'
  },
  {
    id: 'English_radiant_girl',
    name: 'Emily',
    language: 'english',
    accent: 'american',
    gender: 'female',
    age: 'young',
    tags: ['social_media', 'entertainment'],
    plan: PlanName.FREE,
    previewUrl: 'https://media.hoox.video/2b585f2e-51f7-43aa-9f71-df4a6ecb4837.mp3',
    mode: 'minimax'
  },
  {
    id: 'English_magnetic_voiced_man',
    name: 'William',
    language: 'english',
    accent: 'american',
    gender: 'male',
    age: 'middle aged',
    tags: ['advertising', 'entertainment'],
    plan: PlanName.FREE,
    previewUrl: 'https://media.hoox.video/f8a97834-3fda-4ba5-af64-959572d81296.mp3',
    mode: 'minimax'
  },
  {
    id: 'English_compelling_lady1',
    name: 'Olivia',
    language: 'english',
    accent: 'american',
    gender: 'female',
    age: 'middle aged',
    tags: ['news', 'narration'],
    plan: PlanName.FREE,
    previewUrl: 'https://media.hoox.video/896d9f73-1bdd-4167-b121-2f636c8ea72f.mp3',
    mode: 'minimax'
  },
  {
    id: 'English_Aussie_Bloke',
    name: 'Jack',
    language: 'english',
    accent: 'australian',
    gender: 'male',
    age: 'middle aged',
    tags: ['conversational', 'entertainment'],
    plan: PlanName.FREE,
    previewUrl: 'https://media.hoox.video/eb12f344-f3b8-4b7b-b72b-87e3a24d77fd.mp3',
    mode: 'minimax'
  },
  {
    id: 'English_Trustworth_Man',
    name: 'Benjamin',
    language: 'english',
    accent: 'american',
    gender: 'male',
    age: 'middle aged',
    tags: ['news', 'documentary'],
    plan: PlanName.FREE,
    previewUrl: 'https://media.hoox.video/3dff610d-cb28-4b30-ba68-dd1b07f46a37.mp3',
    mode: 'minimax'
  },
  {
    id: 'English_CalmWoman',
    name: 'Grace',
    language: 'english',
    accent: 'american',
    gender: 'female',
    age: 'middle aged',
    tags: ['meditation', 'wellness'],
    plan: PlanName.FREE,
    previewUrl: 'https://media.hoox.video/803e2ae2-7873-4528-9402-d351e97e2400.mp3',
    mode: 'minimax'
  },
  {
    id: 'English_Graceful_Lady',
    name: 'Charlotte',
    language: 'english',
    accent: 'american',
    gender: 'female',
    age: 'middle aged',
    tags: ['narration', 'storytelling'],
    plan: PlanName.FREE,
    previewUrl: 'https://media.hoox.video/1500d57b-8dc7-41e6-a987-353a01071bd2.mp3',
    mode: 'minimax'
  },
  {
    id: 'English_CaptivatingStoryteller',
    name: 'Henry',
    language: 'english',
    accent: 'american',
    gender: 'male',
    age: 'middle aged',
    tags: ['storytelling', 'narration'],
    plan: PlanName.FREE,
    previewUrl: 'https://media.hoox.video/866dcd2c-1e03-4005-a5a4-4b26cca8d659.mp3',
    mode: 'minimax'
  },
  {
    id: 'English_ConfidentWoman',
    name: 'Sophia',
    language: 'english',
    accent: 'american',
    gender: 'female',
    age: 'middle aged',
    tags: ['business', 'news'],
    plan: PlanName.FREE,
    previewUrl: 'https://media.hoox.video/2284c084-7516-4f47-bcda-6f45b7e241cc.mp3',
    mode: 'minimax'
  },
  {
    id: '21m00Tcm4TlvDq8ikWAM',
    name: 'Rachel',
    language: 'english',
    accent: 'american',
    gender: 'female',
    age: 'young',
    tags: ['narration'],
    plan: PlanName.START,
    previewUrl: 'https://storage.googleapis.com/eleven-public-prod/premade/voices/21m00Tcm4TlvDq8ikWAM/df6788f9-5c96-470d-8312-aab3b3d8f50a.mp3',
    mode: 'elevenlabs'
  },
  {
    id: 'CwhRBWXzGAHq8TQ4Fs17',
    name: 'Roger',
    language: 'english',
    accent: 'american',
    gender: 'male',
    age: 'middle aged',
    tags: ['social_media'],
    plan: PlanName.START,
    previewUrl: 'https://storage.googleapis.com/eleven-public-prod/premade/voices/CwhRBWXzGAHq8TQ4Fs17/58ee3ff5-f6f2-4628-93b8-e38eb31806b0.mp3',
    mode: 'elevenlabs'
  },
  {
    id: 'FGY2WhTYpPnrIDTdsKH5',
    name: 'Laura',
    language: 'english',
    accent: 'american',
    gender: 'female',
    age: 'young',
    tags: ['social_media'],
    plan: PlanName.START,
    previewUrl: 'https://storage.googleapis.com/eleven-public-prod/premade/voices/FGY2WhTYpPnrIDTdsKH5/67341759-ad08-41a5-be6e-de12fe448618.mp3',
    mode: 'elevenlabs'
  },
  {
    id: '29vD33N1CtxCmqQRPOHJ',
    name: 'Drew',
    language: 'english',
    accent: 'american',
    gender: 'male',
    age: 'middle aged',
    tags: ['news'],
    plan: PlanName.START,
    previewUrl: 'https://storage.googleapis.com/eleven-public-prod/premade/voices/29vD33N1CtxCmqQRPOHJ/e8b52a3f-9732-440f-b78a-16d5e26407a1.mp3',
    mode: 'elevenlabs'
  },
  {
    id: '2EiwWnXFnvU5JabPnv8n',
    name: 'Clyde',
    language: 'english',
    accent: 'american',
    gender: 'male',
    age: 'middle aged',
    tags: ['video-game'],
    plan: PlanName.START,
    previewUrl: 'https://storage.googleapis.com/eleven-public-prod/premade/voices/2EiwWnXFnvU5JabPnv8n/65d80f52-703f-4cae-a91d-75d4e200ed02.mp3',
    mode: 'elevenlabs'
  },
  {
    id: 'SAz9YHcvj6GT2YYXdXww',
    name: 'River',
    language: 'english',
    accent: 'american',
    gender: 'female',
    age: 'middle aged',
    tags: ['social_media'],
    plan: PlanName.START,
    previewUrl: 'https://storage.googleapis.com/eleven-public-prod/premade/voices/SAz9YHcvj6GT2YYXdXww/e6c95f0b-2227-491a-b3d7-2249240decb7.mp3',
    mode: 'elevenlabs'
  },
  {
    id: 'French_Male_Speech_New',
    name: 'Pierre',
    language: 'french',
    accent: 'french',
    gender: 'male',
    age: 'middle aged',
    tags: ['news', 'documentary'],
    plan: PlanName.FREE,
    previewUrl: 'https://media.hoox.video/2a480f4c-fb8f-4acc-ac2a-770dfce85b5a.mp3',
    mode: 'minimax'
  },
  {
    id: 'French_Female_News Anchor',
    name: 'Marie',
    language: 'french',
    accent: 'french',
    gender: 'female',
    age: 'middle aged',
    tags: ['news', 'journalism'],
    plan: PlanName.FREE,
    previewUrl: 'https://media.hoox.video/2a096860-8e9e-4a1d-8beb-ebc7a2477ef2.mp3',
    mode: 'minimax'
  },
  {
    id: 'French_MovieLeadFemale',
    name: 'Julie',
    language: 'french',
    accent: 'french',
    gender: 'female',
    age: 'young',
    tags: ['entertainment', 'storytelling'],
    plan: PlanName.FREE,
    previewUrl: 'https://media.hoox.video/8f0cbfba-ac3e-4227-85b8-eeef568ed407.mp3',
    mode: 'minimax'
  },
  {
    id: 'French_MaleNarrator',
    name: 'Luc',
    language: 'french',
    accent: 'french',
    gender: 'male',
    age: 'middle aged',
    tags: ['narration', 'storytelling'],
    plan: PlanName.FREE,
    previewUrl: 'https://media.hoox.video/5fc21166-d4fa-453a-82bd-4e2e077d6119.mp3',
    mode: 'minimax'
  },
  {
    id: 'AmMsHJaCw4BtwV3KoUXF',
    name: 'Nicolas',
    language: 'french',
    accent: 'french',
    gender: 'male',
    age: 'middle aged',
    tags: ['news', 'video-game'],
    plan: PlanName.PRO,
    voiceSettings: {
        stability: 0.78,
        similarity_boost: 0.70
    },
    previewUrl: 'https://storage.googleapis.com/eleven-public-prod/1Mn4lcdhvCTTZOJZAqLZXhDzI913/voices/AmMsHJaCw4BtwV3KoUXF/dcfdf987-abaa-4677-bf1c-bd62db878c41.mp3',
    mode: 'elevenlabs'
  },
  {
    id: 'hv6gVog5LgtIUX88Nmq8',
    name: 'Tristan',
    language: 'french',
    accent: 'french',
    gender: 'male',
    age: 'young',
    tags: ['story'],
    plan: PlanName.PRO,
    voiceSettings: {
        stability: 0.99,
        similarity_boost: 0.90
    },
    previewUrl: 'https://storage.googleapis.com/eleven-public-prod/custom/voices/hv6gVog5LgtIUX88Nmq8/tx8rwfCue7TqWMKmoWLv.mp3',
    mode: 'elevenlabs'
  },
  {
    id: 'IHngRooVccHyPqB4uQkG',
    name: 'Corentin',
    language: 'french',
    accent: 'french',
    gender: 'male',
    age: 'young',
    tags: ['social_media'],
    plan: PlanName.ENTREPRISE,
    voiceSettings: {
        stability: 0.52,
        similarity_boost: 0.67
    },
    previewUrl: 'https://storage.googleapis.com/eleven-public-prod/custom/voices/IHngRooVccHyPqB4uQkG/yQPlGmXFNsSO01HV7Qsk.mp3',
    mode: 'elevenlabs'
  },
  {
    id: 'wyZnrAs18zdIj8UgFSV8',
    name: 'Martin',
    language: 'french',
    accent: 'french',
    gender: 'male',
    age: 'middle aged',
    tags: ['story'],
    plan: PlanName.PRO,
    previewUrl: 'https://storage.googleapis.com/eleven-public-prod/custom/voices/wyZnrAs18zdIj8UgFSV8/DriAKIJgOzTr1mTMinLI.mp3',
    mode: 'elevenlabs'
  },
  {
    id: 'Spanish_SereneWoman',
    name: 'Carmen',
    language: 'spanish',
    accent: 'spanish',
    gender: 'female',
    age: 'middle aged',
    tags: ['meditation', 'wellness'],
    plan: PlanName.FREE,
    previewUrl: 'https://media.hoox.video/0b5c036c-5b25-4b29-b279-6b25ea12e7cc.mp3',
    mode: 'minimax'
  },
  {
    id: 'Spanish_CaptivatingStoryteller',
    name: 'Juan',
    language: 'spanish',
    accent: 'spanish',
    gender: 'male',
    age: 'middle aged',
    tags: ['storytelling', 'narration'],
    plan: PlanName.FREE,
    previewUrl: 'https://media.hoox.video/f998d149-b1ea-4de9-8986-29fd309183c9.mp3',
    mode: 'minimax'
  },
  {
    id: 'Spanish_ConfidentWoman',
    name: 'Lucia',
    language: 'spanish',
    accent: 'spanish',
    gender: 'female',
    age: 'middle aged',
    tags: ['business', 'news'],
    plan: PlanName.FREE,
    previewUrl: 'https://media.hoox.video/33cb8a1d-0812-42b9-9de6-a3ec716b9dbc.mp3',
    mode: 'minimax'
  },
  {
    id: 'D7dkYvH17OKLgp4SLulf',
    name: 'Diego',
    language: 'spanish',
    accent: 'spanish',
    gender: 'male',
    age: 'middle aged',
    tags: ['advertising'],
    plan: PlanName.START,
    previewUrl: 'https://storage.googleapis.com/eleven-public-prod/custom/voices/D7dkYvH17OKLgp4SLulf/Fi93KkolvadvCJVGsgqE.mp3',
    mode: 'elevenlabs'
  },
  {
    id: 'ThT5KcBeYPX3keUQqHPh',
    name: 'Dorothy',
    language: 'english',
    accent: 'british',
    gender: 'female',
    age: 'young',
    tags: ['children_stories'],
    plan: PlanName.START,
    previewUrl: 'https://storage.googleapis.com/eleven-public-prod/premade/voices/ThT5KcBeYPX3keUQqHPh/981f0855-6598-48d2-9f8f-b6d92fbbe3fc.mp3',
    mode: 'elevenlabs'
  },
  {
    id: 'KmqhNPEmmOndTBOPk4mJ',
    name: 'Lucie',
    language: 'french',
    accent: 'french',
    gender: 'female',
    age: 'young',
    tags: ['children_stories'],
    plan: PlanName.PRO,
    voiceSettings: {
        stability: 0.42,
        similarity_boost: 0.75
    },
    previewUrl: 'https://storage.googleapis.com/eleven-public-prod/database/user/Zj9ZLb9VaXcqr3nC8n9J55ADmaB2/voices/KmqhNPEmmOndTBOPk4mJ/Q2N4SM2u9Rc5dlcx4ZvR.mp3',
    mode: 'elevenlabs'
  },
  {
    id: 'dllHSct4GokGc1AH9JwT',
    name: 'Haseeb',
    language: 'french',
    accent: 'canadian',
    gender: 'male',
    age: 'young',
    tags: ['entertainment'],
    plan: PlanName.PRO,
    previewUrl: 'https://storage.googleapis.com/eleven-public-prod/custom/voices/dllHSct4GokGc1AH9JwT/JXj5A2pcLMsfU01VbiHN.mp3',
    mode: 'elevenlabs'
  },
  {
    id: 'MNKK2Wl2wbbsEPQTHZGt',
    name: 'Margaux',
    language: 'french',
    accent: 'french',
    gender: 'female',
    age: 'middle aged',
    tags: ['story', 'social_media', 'conversational'],
    plan: PlanName.ENTREPRISE,
    previewUrl: 'https://storage.googleapis.com/eleven-public-prod/database/user/koOonD4HAsSMVyHuP4QTaatQ9cA2/voices/MNKK2Wl2wbbsEPQTHZGt/cBESg5mfxRaw8hEM3XnT.mp3',
    mode: 'elevenlabs'
  },
  {
    id: 'TnnHlREp9UyW7nQDycZx',
    name: 'Alexandre',
    language: 'french',
    accent: 'french',
    gender: 'male',
    age: 'middle aged',
    tags: ['advertising'],
    plan: PlanName.ENTREPRISE,
    voiceSettings: {
        stability: 1,
        similarity_boost: 0.75
    },
    previewUrl: 'https://storage.googleapis.com/eleven-public-prod/database/user/PZVKCR3CEIRXaGs4kAkaa6xW9gu2/voices/TnnHlREp9UyW7nQDycZx/zd4Now7NNZt7XTpQfowW.mp3',
    mode: 'elevenlabs'
  },
  {
    id: '5Q0t7uMcjvnagumLfvZi',
    name: 'Paul',
    language: 'english',
    accent: 'american',
    gender: 'male',
    age: 'middle aged',
    tags: ['news'],
    plan: PlanName.START,
    previewUrl: 'https://storage.googleapis.com/eleven-public-prod/premade/voices/5Q0t7uMcjvnagumLfvZi/1094515a-b080-4282-aac7-b1b8a553a3a8.mp3',
    mode: 'elevenlabs'
  },
  {
    id: 'AZnzlk1XvdvUeBnXmlld',
    name: 'Domi',
    language: 'english',
    accent: 'american',
    gender: 'female',
    age: 'young',
    tags: ['narration'],
    plan: PlanName.START,
    previewUrl: 'https://storage.googleapis.com/eleven-public-prod/premade/voices/AZnzlk1XvdvUeBnXmlld/508e12d0-a7f7-4d86-a0d3-f3884ff353ed.mp3',
    mode: 'elevenlabs'
  },
  {
    id: 'CYw3kZ02Hs0563khs1Fj',
    name: 'Dave',
    language: 'english',
    accent: 'british',
    gender: 'male',
    age: 'young',
    tags: ['video-game'],
    plan: PlanName.START,
    previewUrl: 'https://storage.googleapis.com/eleven-public-prod/premade/voices/CYw3kZ02Hs0563khs1Fj/872cb056-45d3-419e-b5c6-de2b387a93a0.mp3',
    mode: 'elevenlabs'
  },
  {
    id: 'D38z5RcWu1voky8WS1ja',
    name: 'Fin',
    language: 'english',
    accent: 'irish',
    gender: 'male',
    age: 'old',
    tags: ['video-game'],
    plan: PlanName.START,
    previewUrl: 'https://storage.googleapis.com/eleven-public-prod/premade/voices/D38z5RcWu1voky8WS1ja/a470ba64-1e72-46d9-ba9d-030c4155e2d2.mp3',
    mode: 'elevenlabs'
  },
  {
    id: 'EXAVITQu4vr4xnSDxMaL',
    name: 'Sarah',
    language: 'english',
    accent: 'american',
    gender: 'female',
    age: 'young',
    tags: ['news'],
    plan: PlanName.START,
    previewUrl: 'https://storage.googleapis.com/eleven-public-prod/premade/voices/EXAVITQu4vr4xnSDxMaL/6851ec91-9950-471f-8586-357c52539069.mp3',
    mode: 'elevenlabs'
  },
  {
    id: 'ErXwobaYiN019PkySvjV',
    name: 'Antoni',
    language: 'english',
    accent: 'american',
    gender: 'male',
    age: 'young',
    tags: ['narration'],
    plan: PlanName.PRO,
    previewUrl: 'https://storage.googleapis.com/eleven-public-prod/premade/voices/ErXwobaYiN019PkySvjV/ee9ac367-91ee-4a56-818a-2bd1a9dbe83a.mp3',
    mode: 'elevenlabs'
  },
  {
    id: 'GBv7mTt0atIp3Br8iCZE',
    name: 'Thomas',
    language: 'english',
    accent: 'american',
    gender: 'male',
    age: 'young',
    tags: ['meditation'],
    plan: PlanName.PRO,
    previewUrl: 'https://storage.googleapis.com/eleven-public-prod/premade/voices/GBv7mTt0atIp3Br8iCZE/98542988-5267-4148-9a9e-baa8c4f14644.mp3',
    mode: 'elevenlabs'
  },
  {
    id: 'IKne3meq5aSn9XLyUdCD',
    name: 'Charlie',
    language: 'english',
    accent: 'australian',
    gender: 'male',
    age: 'middle aged',
    tags: ['conversational'],
    plan: PlanName.PRO,
    previewUrl: 'https://storage.googleapis.com/eleven-public-prod/premade/voices/IKne3meq5aSn9XLyUdCD/102de6f2-22ed-43e0-a1f1-111fa75c5481.mp3',
    mode: 'elevenlabs'
  },
  {
    id: 'JBFqnCBsd6RMkjVDRZzb',
    name: 'George',
    language: 'english',
    accent: 'british',
    gender: 'male',
    age: 'middle aged',
    tags: ['narration'],
    plan: PlanName.START,
    previewUrl: 'https://storage.googleapis.com/eleven-public-prod/premade/voices/JBFqnCBsd6RMkjVDRZzb/e6206d1a-0721-4787-aafb-06a6e705cac5.mp3',
    mode: 'elevenlabs'
  },
  {
    id: 'LcfcDJNUP1GQjkzn1xUU',
    name: 'Emily',
    language: 'english',
    accent: 'american',
    gender: 'female',
    age: 'young',
    tags: ['meditation'],
    plan: PlanName.START,
    previewUrl: 'https://storage.googleapis.com/eleven-public-prod/premade/voices/LcfcDJNUP1GQjkzn1xUU/e4b994b7-9713-4238-84f3-add8fccaaccd.mp3',
    mode: 'elevenlabs'
  },
  {
    id: 'MF3mGyEYCl7XYWbV9V6O',
    name: 'Elli',
    language: 'english',
    accent: 'american',
    gender: 'female',
    age: 'young',
    tags: ['narration', 'news'],
    plan: PlanName.START,
    previewUrl: 'https://storage.googleapis.com/eleven-public-prod/premade/voices/MF3mGyEYCl7XYWbV9V6O/d8ecadea-9e48-4e5d-868a-2ec3d7397861.mp3',
    mode: 'elevenlabs'
  },
  {
    id: 'N2lVS1w4EtoT3dr4eOWO',
    name: 'Callum',
    language: 'english',
    accent: 'american',
    gender: 'male',
    age: 'middle aged',
    tags: ['characters'],
    plan: PlanName.PRO,
    previewUrl: 'https://storage.googleapis.com/eleven-public-prod/premade/voices/N2lVS1w4EtoT3dr4eOWO/ac833bd8-ffda-4938-9ebc-b0f99ca25481.mp3',
    mode: 'elevenlabs'
  },
  {
    id: 'ODq5zmih8GrVes37Dizd',
    name: 'Patrick',
    language: 'english',
    accent: 'american',
    gender: 'male',
    age: 'middle aged',
    tags: ['video-game'],
    plan: PlanName.PRO,
    previewUrl: 'https://storage.googleapis.com/eleven-public-prod/premade/voices/ODq5zmih8GrVes37Dizd/0ebec87a-2569-4976-9ea5-0170854411a9.mp3',
    mode: 'elevenlabs'
  },
  {
    id: 'SOYHLrjzK2X1ezoPC6cr',
    name: 'Harry',
    language: 'english',
    accent: 'american',
    gender: 'male',
    age: 'young',
    tags: ['video-game'],
    plan: PlanName.PRO,
    previewUrl: 'https://storage.googleapis.com/eleven-public-prod/premade/voices/SOYHLrjzK2X1ezoPC6cr/86d178f6-f4b6-4e0e-85be-3de19f490794.mp3',
    mode: 'elevenlabs'
  },
  {
    id: 'TX3LPaxmHKxFdv7VOQHJ',
    name: 'Liam',
    language: 'english',
    accent: 'american',
    gender: 'male',
    age: 'young',
    tags: ['narration'],
    plan: PlanName.PRO,
    previewUrl: 'https://storage.googleapis.com/eleven-public-prod/premade/voices/TX3LPaxmHKxFdv7VOQHJ/63148076-6363-42db-aea8-31424308b92c.mp3',
    mode: 'elevenlabs'
  },
  {
    id: 'TxGEqnHWrfWFTfGW9XjX',
    name: 'Josh',
    language: 'english',
    accent: 'american',
    gender: 'male',
    age: 'young',
    tags: ['narration'],
    plan: PlanName.PRO,
    previewUrl: 'https://storage.googleapis.com/eleven-public-prod/premade/voices/TxGEqnHWrfWFTfGW9XjX/3ae2fc71-d5f9-4769-bb71-2a43633cd186.mp3',
    mode: 'elevenlabs'
  },
  {
    id: 'VR6AewLTigWG4xSOukaG',
    name: 'Arnold',
    language: 'english',
    accent: 'american',
    gender: 'male',
    age: 'middle aged',
    tags: ['narration'],
    plan: PlanName.PRO,
    previewUrl: 'https://storage.googleapis.com/eleven-public-prod/premade/voices/VR6AewLTigWG4xSOukaG/316050b7-c4e0-48de-acf9-a882bb7fc43b.mp3',
    mode: 'elevenlabs'
  },
  {
    id: 'XB0fDUnXU5powFXDhCwa',
    name: 'Charlotte',
    language: 'english',
    accent: 'swedish',
    gender: 'female',
    age: 'young',
    tags: ['characters'],
    plan: PlanName.PRO,
    previewUrl: 'https://storage.googleapis.com/eleven-public-prod/premade/voices/XB0fDUnXU5powFXDhCwa/942356dc-f10d-4d89-bda5-4f8505ee038b.mp3',
    mode: 'elevenlabs'
  },
  {
    id: 'Xb7hH8MSUJpSbSDYk0k2',
    name: 'Alice',
    language: 'english',
    accent: 'british',
    gender: 'female',
    age: 'middle aged',
    tags: ['news'],
    plan: PlanName.PRO,
    previewUrl: 'https://storage.googleapis.com/eleven-public-prod/premade/voices/Xb7hH8MSUJpSbSDYk0k2/d10f7534-11f6-41fe-a012-2de1e482d336.mp3',
    mode: 'elevenlabs'
  },
  {
    id: 'XrExE9yKIg1WjnnlVkGX',
    name: 'Matilda',
    language: 'english',
    accent: 'american',
    gender: 'female',
    age: 'middle aged',
    tags: ['narration'],
    plan: PlanName.PRO,
    previewUrl: 'https://storage.googleapis.com/eleven-public-prod/premade/voices/XrExE9yKIg1WjnnlVkGX/b930e18d-6b4d-466e-bab2-0ae97c6d8535.mp3',
    mode: 'elevenlabs'
  },
  {
    id: 'ZQe5CZNOzWyzPSCn5a3c',
    name: 'James',
    language: 'english',
    accent: 'australian',
    gender: 'male',
    age: 'old',
    tags: ['news'],
    plan: PlanName.PRO,
    previewUrl: 'https://storage.googleapis.com/eleven-public-prod/premade/voices/ZQe5CZNOzWyzPSCn5a3c/35734112-7b72-48df-bc2f-64d5ab2f791b.mp3',
    mode: 'elevenlabs'
  },
  {
    id: 'Zlb1dXrM653N07WRdFW3',
    name: 'Joseph',
    language: 'english',
    accent: 'british',
    gender: 'male',
    age: 'middle aged',
    tags: ['news'],
    plan: PlanName.PRO,
    previewUrl: 'https://storage.googleapis.com/eleven-public-prod/premade/voices/Zlb1dXrM653N07WRdFW3/daa22039-8b09-4c65-b59f-c79c48646a72.mp3',
    mode: 'elevenlabs'
  },
  {
    id: 'bVMeCyTHy58xNoL34h3p',
    name: 'Jeremy',
    language: 'english',
    accent: 'irish',
    gender: 'male',
    age: 'young',
    tags: ['narration'],
    plan: PlanName.PRO,
    previewUrl: 'https://storage.googleapis.com/eleven-public-prod/premade/voices/bVMeCyTHy58xNoL34h3p/66c47d58-26fd-4b30-8a06-07952116a72c.mp3',
    mode: 'elevenlabs'
  },
  {
    id: 'bIHbv24MWmeRgasZH58o',
    name: 'Will',
    language: 'english',
    accent: 'american',
    gender: 'male',
    age: 'young',
    tags: ['social_media'],
    plan: PlanName.PRO,
    previewUrl: 'https://storage.googleapis.com/eleven-public-prod/premade/voices/bIHbv24MWmeRgasZH58o/8caf8f3d-ad29-4980-af41-53f20c72d7a4.mp3',
    mode: 'elevenlabs'
  },
  {
    id: 'cgSgspJ2msm6clMCkdW9',
    name: 'Jessica',
    language: 'english',
    accent: 'american',
    gender: 'female',
    age: 'young',
    tags: ['conversational', 'advertising'],
    plan: PlanName.PRO,
    previewUrl: 'https://storage.googleapis.com/eleven-public-prod/premade/voices/cgSgspJ2msm6clMCkdW9/56a97bf8-b69b-448f-846c-c3a11683d45a.mp3',
    mode: 'elevenlabs'
  },
  {
    id: 'cjVigY5qzO86Huf0OWal',
    name: 'Eric',
    language: 'english',
    accent: 'american',
    gender: 'male',
    age: 'middle aged',
    tags: ['conversational'],
    plan: PlanName.PRO,
    previewUrl: 'https://storage.googleapis.com/eleven-public-prod/premade/voices/cjVigY5qzO86Huf0OWal/d098fda0-6456-4030-b3d8-63aa048c9070.mp3',
    mode: 'elevenlabs'
  },
  {
    id: 'qlfxsYlCv09qu8y6PkmY',
    name: 'Sébastien',
    language: 'french',
    accent: 'french',
    gender: 'male',
    age: 'middle aged',
    tags: ['advertising'],
    plan: PlanName.START,
    previewUrl: 'https://storage.googleapis.com/eleven-public-prod/database/user/IDjAiYAPz8WIBA9QLchInFTST2K2/voices/qlfxsYlCv09qu8y6PkmY/IUx8b3i3dkhJvQekActS.mp3',
    mode: 'elevenlabs'
  },
  {
    id: 'flq6f7yk4E4fJM5XTYuZ',
    name: 'Michael',
    language: 'english',
    accent: 'american',
    gender: 'male',
    age: 'old',
    tags: ['audiobook'],
    plan: PlanName.PRO,
    previewUrl: 'https://storage.googleapis.com/eleven-public-prod/premade/voices/flq6f7yk4E4fJM5XTYuZ/c6431a82-f7d2-4905-b8a4-a631960633d6.mp3',
    mode: 'elevenlabs'
  },
  {
    id: 'g5CIjZEefAph4nQFvHAz',
    name: 'Ethan',
    language: 'english',
    accent: 'american',
    gender: 'male',
    age: 'young',
    tags: ['ASMR'],
    plan: PlanName.PRO,
    previewUrl: 'https://storage.googleapis.com/eleven-public-prod/premade/voices/g5CIjZEefAph4nQFvHAz/26acfa99-fdec-43b8-b2ee-e49e75a3ac16.mp3',
    mode: 'elevenlabs'
  },
  {
    id: 'jBpfuIE2acCO8z3wKNLl',
    name: 'Gigi',
    language: 'english',
    accent: 'american',
    gender: 'female',
    age: 'young',
    tags: ['animation'],
    plan: PlanName.PRO,
    previewUrl: 'https://storage.googleapis.com/eleven-public-prod/premade/voices/jBpfuIE2acCO8z3wKNLl/3a7e4339-78fa-404e-8d10-c3ef5587935b.mp3',
    mode: 'elevenlabs'
  },
  {
    id: 'jsCqWAovK2LkecY7zXl4',
    name: 'Freya',
    language: 'english',
    accent: 'american',
    gender: 'female',
    age: 'young',
    tags: ['social_media'],
    plan: PlanName.PRO,
    previewUrl: 'https://storage.googleapis.com/eleven-public-prod/premade/voices/jsCqWAovK2LkecY7zXl4/8e1f5240-556e-4fd5-892c-25df9ea3b593.mp3',
    mode: 'elevenlabs'
  },
  {
    id: 'German_FriendlyMan',
    name: 'Lukas',
    language: 'german',
    accent: 'german',
    gender: 'male',
    age: 'middle aged',
    tags: ['conversational', 'entertainment'],
    plan: PlanName.FREE,
    previewUrl: 'https://media.hoox.video/2ce0d013-65ce-40db-b01f-6827ea5cd630.mp3',
    mode: 'minimax'
  },
  {
    id: 'German_SweetLady',
    name: 'Anna',
    language: 'german',
    accent: 'german',
    gender: 'female',
    age: 'middle aged',
    tags: ['storytelling', 'narration'],
    plan: PlanName.FREE,
    previewUrl: 'https://media.hoox.video/c69570ba-a14e-4b69-b5be-35b00daa890e.mp3',
    mode: 'minimax'
  },
  {
    id: 'y8FeN9lFTEmQOYCaE07F',
    name: 'Amadeus',
    language: 'german',
    accent: 'german',
    gender: 'male',
    age: 'middle aged',
    tags: ['story'],
    plan: PlanName.ENTREPRISE,
    previewUrl: 'https://storage.googleapis.com/eleven-public-prod/custom/voices/y8FeN9lFTEmQOYCaE07F/9bxoWAk64KX3ReXWWxzF.mp3',
    mode: 'elevenlabs'
  },
  {
    id: 'yl2ZDV1MzN4HbQJbMihG',
    name: 'Alex',
    language: 'english',
    accent: 'american',
    gender: 'male',
    age: 'young',
    tags: ['social_media', 'entertainment'],
    plan: PlanName.PRO,
    previewUrl: 'https://storage.googleapis.com/eleven-public-prod/custom/voices/yl2ZDV1MzN4HbQJbMihG/TxJIOexqYqCv1Dzexs6Y.mp3',
    mode: 'elevenlabs'
  },
  {
    id: 'wcGcDDfRHvH6LR9p07u4',
    name: 'Apollo',
    language: 'german',
    accent: 'german',
    gender: 'male',
    age: 'young',
    tags: ['documentary', 'tv'],
    plan: PlanName.ENTREPRISE,
    previewUrl: 'https://storage.googleapis.com/eleven-public-prod/custom/voices/wcGcDDfRHvH6LR9p07u4/MwCrcs1GOzSgvpRzteGO.mp3',
    mode: 'elevenlabs'
  },
  {
    id: '7H4vk4UjjbKDZiGTgH8K',
    name: 'DellaRayne',
    language: 'english',
    accent: 'american', 
    gender: 'female',
    age: 'middle aged',
    tags: ['news', 'social_media'],
    plan: PlanName.ENTREPRISE,
    previewUrl: 'https://storage.googleapis.com/eleven-public-prod/database/user/cRXPVHkjb5YtcgDRqlqIZ9N7AdP2/voices/7H4vk4UjjbKDZiGTgH8K/tmQekACAPn5p2i4Z4Jtu.mp3',
    mode: 'elevenlabs'
  },
  {
    id: 'rpw80tAFDqIOQ0Ve2QVJ',
    name: 'Fred',
    language: 'french',
    accent: 'french',
    gender: 'male',
    age: 'middle aged',
    tags: ['entertainment'],
    plan: PlanName.PRO,
    previewUrl: 'https://storage.googleapis.com/eleven-public-prod/LhidVU2Rn4OyolheNv4hiKZPyJj1/voices/rpw80tAFDqIOQ0Ve2QVJ/9a88462c-d0be-4d15-8443-fbf1c5fa7da7.mp3',
    mode: 'elevenlabs'
  },
  {
    id: 'ohItIVrXTBI80RrUECOD',
    name: 'Guillaume',
    language: 'french',
    accent: 'french',
    gender: 'male',
    age: 'middle aged',
    tags: ['narration'],
    plan: PlanName.PRO,
    previewUrl: 'https://storage.googleapis.com/eleven-public-prod/custom/voices/ohItIVrXTBI80RrUECOD/9mwgJwmYqekI6JTMJTcv.mp3',
    mode: 'elevenlabs'
  },
  {
    id: 'GgV5QStPLpmkN7FOHJtY',
    name: 'Peter',
    language: 'french',
    accent: 'french',
    gender: 'male',
    age: 'young',
    tags: ['narration', 'educational'],
    plan: PlanName.PRO,
    voiceSettings: {
        stability: 0.52,
        similarity_boost: 1
    },
    previewUrl: 'https://storage.googleapis.com/eleven-public-prod/custom/voices/GgV5QStPLpmkN7FOHJtY/bmKBkANSoceD0lpX6ZiA.mp3',
    mode: 'elevenlabs'
  },
  {
    id: '9BWtsMINqrJLrRacOk9x',
    name: 'Aria',
    language: 'english',
    accent: 'american',
    gender: 'female',
    age: 'middle aged',
    tags: ['social_media'],
    plan: PlanName.START,
    previewUrl: 'https://storage.googleapis.com/eleven-public-prod/premade/voices/9BWtsMINqrJLrRacOk9x/405766b8-1f4e-4d3c-aba1-6f25333823ec.mp3',
    mode: 'elevenlabs'
  },
  {
    id: 'FpvROcY4IGWevepmBWO2',
    name: 'Jessy',
    language: 'french',
    accent: 'french',
    gender: 'female',
    age: 'young',
    tags: ['journalism', 'entertainment'],
    plan: PlanName.PRO,
    previewUrl: 'https://storage.googleapis.com/eleven-public-prod/database/user/ZAS4o4vI8aVeceS8bWmtpuSYDqM2/voices/FpvROcY4IGWevepmBWO2/bS9p4qTvVCRqxuIqhvk3.mp3',
    mode: 'elevenlabs'
  },
  {
    id: 'PBm6YPbx7WbrxFTZwj3E',
    name: 'Gabriel',
    language: 'french',
    accent: 'french',
    gender: 'male',
    age: 'middle aged',
    tags: ['audiobooks', 'podcast', 'storytelling'],
    plan: PlanName.PRO,
    previewUrl: 'https://storage.googleapis.com/eleven-public-prod/custom/voices/PBm6YPbx7WbrxFTZwj3E/D8U7C2MgPxZt3MVgeFjn.mp3',
    mode: 'elevenlabs'
  },
  {
    id: 'hPrNlxoc73WWsa2Bn4Xl',
    name: 'Jessica',
    language: 'english',
    accent: 'american',
    gender: 'female',
    age: 'young',
    tags: ['narration'],
    plan: PlanName.PRO,
    previewUrl: 'https://storage.googleapis.com/eleven-public-prod/premade/voices/hPrNlxoc73WWsa2Bn4Xl/1ac32982-cda7-45e9-a8ae-1dc7e0654c7e.mp3',
    mode: 'elevenlabs'
  },
  {
    id: 'pNInz6obpgDQGcFmaJgB',
    name: 'Adam',
    language: 'english',
    accent: 'american',
    gender: 'male',
    age: 'middle aged',
    tags: ['audiobook', 'documentary'],
    plan: PlanName.PRO,
    previewUrl: 'https://storage.googleapis.com/eleven-public-prod/premade/voices/pNInz6obpgDQGcFmaJgB/00a07690-41ef-4b37-9877-3521877fb517.mp3',
    mode: 'elevenlabs'
  },
  {
    id: 'zcAOhNBS3c14rBihAFp1',
    name: 'Lucas',
    language: 'french',
    accent: 'french',
    gender: 'male',
    age: 'young',
    tags: ['narration', 'podcast'],
    plan: PlanName.PRO,
    previewUrl: 'https://storage.googleapis.com/eleven-public-prod/UeKvUoSIoHPIPa1EC4SF7awTS1O2/voices/zcAOhNBS3c14rBihAFp1/c0c8eb52-57f4-4e0c-bbb1-4132c68583bc.mp3',
    mode: 'elevenlabs'
  },
  {
    id: 'XpgPp3EWdH9jutj6iYCG',
    name: 'Juliette',
    language: 'french',
    accent: 'french',
    gender: 'female',
    age: 'young',
    tags: ['narration', 'storytelling'],
    plan: PlanName.PRO,
    previewUrl: 'https://storage.googleapis.com/eleven-public-prod/custom/voices/XpgPp3EWdH9jutj6iYCG/u0ahKTZK04PQzfRFMYNT.mp3',
    mode: 'elevenlabs'
  },
  {
    id: 'Lj1QjnOhnCRYdZ1z41yA',
    name: 'Max',
    language: 'german',
    accent: 'german',
    gender: 'male',
    age: 'young',
    tags: ['news', 'documentary'],
    plan: PlanName.PRO,
    previewUrl: 'https://storage.googleapis.com/eleven-public-prod/custom/voices/Lj1QjnOhnCRYdZ1z41yA/NXGVXlbtcwI6fTuGHO5H.mp3',
    mode: 'elevenlabs'
  },
  {
    id: 'WuBPEavIaQB56EnsGvFh',
    name: 'Eryn',
    language: 'english',
    accent: 'american',
    gender: 'female',
    age: 'young',
    tags: ['news', 'documentary'],
    plan: PlanName.ENTREPRISE,
    previewUrl: 'https://storage.googleapis.com/eleven-public-prod/database/user/DdUt6lVFfrUOSikHrCbs3tesMgE2/voices/WuBPEavIaQB56EnsGvFh/3TZ2U2i8QlJlMuv3IEwF.mp3',
    mode: 'elevenlabs'
  },
  {
    id: 'DbbNuBL7lf62XwY7arQb',
    name: 'Hugo',
    language: 'french',
    accent: 'french',
    gender: 'male',
    age: 'young',
    tags: ['advertising'],
    plan: PlanName.PRO,
    previewUrl: 'https://storage.googleapis.com/eleven-public-prod/database/user/CnqbtUuTI7c3c9tg8rabjLsxs392/voices/DbbNuBL7lf62XwY7arQb/SWJaCUjKugbzdtfB3K5g.mp3',
    mode: 'elevenlabs'
  },
  {
    id: 'exxAZVMfY4Qs7F9CS1oN',
    name: 'Mikulai',
    language: 'english',
    accent: 'croatian',
    gender: 'male',
    age: 'middle aged',
    tags: ['narration'],
    plan: PlanName.ENTREPRISE,
    previewUrl: 'https://storage.googleapis.com/eleven-public-prod/database/user/nhgk7oBcbxQC2q60UkxTfqILyJH2/voices/exxAZVMfY4Qs7F9CS1oN/85e5d7bf-1951-40ad-a895-aa36315a5eb9.mp3',
    mode: 'elevenlabs'
  },
  {
    id: '991lF4hc0xxfec4Y6B0i',
    name: 'Henry',
    language: 'english',
    accent: 'british',
    gender: 'male',
    age: 'middle aged',
    tags: ['narration'],
    plan: PlanName.PRO,
    previewUrl: 'https://storage.googleapis.com/eleven-public-prod/database/user/xkeMToCFOISTDezVTilP578UL8P2/voices/991lF4hc0xxfec4Y6B0i/nRrBNvwlFicCbjCwWpDU.mp3',
    mode: 'elevenlabs'
  },
  {
    id: 'GBp66gF5eXCkPPSbXSDf',
    name: 'Fabien',
    language: 'french',
    accent: 'french',
    gender: 'male',
    age: 'middle aged',
    tags: ['narration'],
    plan: PlanName.PRO,
    previewUrl: 'https://storage.googleapis.com/eleven-public-prod/database/user/7ucN3eeqpmVgx1aioqv50fxHYUy1/voices/GBp66gF5eXCkPPSbXSDf/0Idsn9IUbSjsPV0e8Blp.mp3',
    mode: 'elevenlabs'
  },
  {
    id: 'it5NMxoQQ2INIh4XcO44',
    name: 'Fisayo',
    language: 'english',
    accent: 'nigerian',
    gender: 'male',
    age: 'young',
    tags: ['narration'],
    plan: PlanName.PRO,
    previewUrl: 'https://storage.googleapis.com/eleven-public-prod/database/user/yQsdngW2YfNcf21J76ZoeHWYWlF3/voices/it5NMxoQQ2INIh4XcO44/614c998f-9650-481e-bf2c-82c07d198c14.mp3',
    mode: 'elevenlabs'
  },
  {
    id: 'byWOh4ohcovt7I8koF2I',
    name: 'Alejandro',
    language: 'spanish',
    accent: 'spanish',
    gender: 'male',
    age: 'young',
    tags: ['narration'],
    plan: PlanName.ENTREPRISE,
    previewUrl: 'https://storage.googleapis.com/eleven-public-prod/database/user/ek2hAMyYf2bduef0Kx4Devyliyp1/voices/byWOh4ohcovt7I8koF2I/opQmsRyg7lcWOXCp1VNS.mp3',
    mode: 'elevenlabs'
  },
  {
    id: 'aUTn6mevnrM9pqtesisb',
    name: 'Aaliyah',
    language: 'hindi',
    accent: 'indian',
    gender: 'female',
    age: 'middle aged',
    tags: ['narration'],
    plan: PlanName.PRO,
    previewUrl: 'https://storage.googleapis.com/eleven-public-prod/database/user/qi0SL35A2VgBnfV6EJ3InVfTK4D3/voices/aUTn6mevnrM9pqtesisb/a6cf4206-bc5e-43d0-9a71-1f33871a7e97.mp3',
    mode: 'elevenlabs'
  },
  {
    id: 'rB5Qp6YdOmuEtJFRdSQ4',
    name: 'Heraldo',
    language: 'spanish',
    accent: 'spanish',
    gender: 'male',
    age: 'middle aged',
    tags: ['narration'],
    plan: PlanName.PRO,
    previewUrl: 'https://storage.googleapis.com/eleven-public-prod/database/user/7rRTLlFFfFWXTG0i2PYea6PMKxU2/voices/rB5Qp6YdOmuEtJFRdSQ4/cfd147f4-f9e1-45f1-a809-4f21f08ce2ec.mp3',
    mode: 'elevenlabs'
  },
  {
    id: 'Italian_Narrator',
    name: 'Marco',
    language: 'italian',
    accent: 'italian',
    gender: 'male',
    age: 'middle aged',
    tags: ['narration', 'storytelling'],
    plan: PlanName.FREE,
    previewUrl: 'https://media.hoox.video/343d1729-3b7a-4b55-84d6-c511e545a49e.mp3',
    mode: 'minimax'
  },
  {
    id: 'Italian_BraveHeroine',
    name: 'Giulia',
    language: 'italian',
    accent: 'italian',
    gender: 'female',
    age: 'young',
    tags: ['entertainment', 'storytelling'],
    plan: PlanName.FREE,
    previewUrl: 'https://media.hoox.video/1a9716bd-a37f-48f5-84f3-1281e8eb16ab.mp3',
    mode: 'minimax'
  },
  {
    id: 'QQpLisLueobAksl21CaK',
    name: 'Vanna Isaia',
    language: 'italian',
    accent: 'italian',
    gender: 'female',
    age: 'middle aged',
    tags: ['narration'],
    plan: PlanName.PRO,
    previewUrl: 'https://storage.googleapis.com/eleven-public-prod/database/user/WIxLfUzQwDefgXJDitEOMmWvdky1/voices/QQpLisLueobAksl21CaK/Q7fFitaSyjYwxx1sJ1dO.mp3',
    mode: 'elevenlabs'
  },
  {
    id: '58SnLsdWOv994RNKXLhV',
    name: 'Dan',
    language: 'english',
    accent: 'american',
    gender: 'male',
    age: 'middle aged',
    tags: ['narration'],
    plan: PlanName.ENTREPRISE,
    previewUrl: 'https://storage.googleapis.com/eleven-public-prod/database/user/DFCSpya3TkNqWrV1PUbXKdcCAXH3/voices/58SnLsdWOv994RNKXLhV/246660cf-85b1-443c-816c-307f9f4c1e54.mp3',
    mode: 'elevenlabs'
  },
  {
    id: 'mFgXOmlOfXfr6suoQkRH',
    name: 'Frances',
    language: 'english',
    accent: 'irish',
    gender: 'female',
    age: 'middle aged',
    tags: ['narration'],
    plan: PlanName.PRO,
    previewUrl: 'https://storage.googleapis.com/eleven-public-prod/database/user/bb3RJYk3MKfoNRCBCd7fDI6pfIg2/voices/mFgXOmlOfXfr6suoQkRH/614ee365-8e51-4545-93a7-0a3338c765f0.mp3',
    mode: 'elevenlabs'
  },
  {
    id: '75toWT7xwWkf5F7xSBgK',
    name: 'omgpvoice',
    language: 'spanish',
    accent: 'spanish',
    gender: 'male',
    age: 'middle aged',
    tags: ['narration'],
    plan: PlanName.ENTREPRISE,
    previewUrl: 'https://storage.googleapis.com/eleven-public-prod/database/user/0Pp4sLTnuHaJOE5r0xCjhGZGHCI2/voices/75toWT7xwWkf5F7xSBgK/0a04be0f-d6c3-427e-ad5e-40b92c8cda74.mp3',
    mode: 'elevenlabs'
  },
  {
    id: '8lbMAldPdNgaVy6tKwSs',
    name: 'Mario',
    language: 'spanish',
    accent: 'spanish',
    gender: 'male',
    age: 'middle aged',
    tags: ['narration'],
    plan: PlanName.PRO,
    previewUrl: 'https://storage.googleapis.com/eleven-public-prod/database/user/ER39kT6PRBRm3Mn1puxCf29gDk22/voices/8lbMAldPdNgaVy6tKwSs/HchxVOKW4Gmw7VJt85y0.mp3',
    mode: 'elevenlabs'
  },
  {
    id: 'CiACFqHhFCzosBy47F4a',
    name: 'Kyle',
    language: 'english',
    accent: 'american',
    gender: 'male',
    age: 'young',
    tags: ['narration'],
    plan: PlanName.PRO,
    previewUrl: 'https://storage.googleapis.com/eleven-public-prod/database/user/IW0luuLA0rfha0Idd9mNs5vD30J2/voices/CiACFqHhFCzosBy47F4a/abce7301-fdd2-466f-9ac2-4dffbb51c65d.mp3',
    mode: 'elevenlabs'
  },
  {
    id: 'orF2qy9215xjwqqxqsWW',
    name: 'Rafael',
    language: 'spanish',
    accent: 'spanish',
    gender: 'male',
    age: 'old',
    tags: ['narration'],
    plan: PlanName.PRO,
    previewUrl: 'https://storage.googleapis.com/eleven-public-prod/database/user/sU82YAs205U4voRAto2MQACX1a12/voices/orF2qy9215xjwqqxqsWW/SJmtVEhMG2bXkGRJXG69.mp3',
    mode: 'elevenlabs'
  },
  {
    id: 'dyLJ4nCukg4AOgAVlUR7',
    name: 'Eli',
    language: 'english',
    accent: 'american',
    gender: 'male',
    age: 'middle aged',
    tags: ['entertainment'],
    plan: PlanName.PRO,
    previewUrl: 'https://storage.googleapis.com/eleven-public-prod/database/user/sU82YAs205U4voRAto2MQACX1a12/voices/orF2qy9215xjwqqxqsWW/SJmtVEhMG2bXkGRJXG69.mp3',
    mode: 'elevenlabs'
  },
  {
    id: 'DveEBhc92f63T1jcpWTx',
    name: 'Waverly',
    language: 'english',
    accent: 'american',
    gender: 'female',
    age: 'middle aged',
    tags: ['narration'],
    plan: PlanName.ENTREPRISE,
    previewUrl: 'https://storage.googleapis.com/eleven-public-prod/database/user/RQNbgmuTlWUvhm0Mnm1nSsI0qXE3/voices/DveEBhc92f63T1jcpWTx/stv26KZlmXKsA8l3NixT.mp3',
    mode: 'elevenlabs'
  },
  {
    id: 'FWCNEHwbQhB1Da2r1GKI',
    name: 'Shane',
    language: 'english',
    accent: 'american',
    gender: 'male',
    age: 'middle aged',
    tags: ['narration'],
    plan: PlanName.PRO,
    previewUrl: 'https://storage.googleapis.com/eleven-public-prod/database/user/ozMB8jrBVqbaUOJusn3iJTWV1FJ3/voices/FWCNEHwbQhB1Da2r1GKI/c165f1c0-28c3-4726-8270-84be1fc4a629.mp3',
    mode: 'elevenlabs'
  },
  {
    id: 'QASMHppTyiZ0ijhb7hy0',
    name: 'Olympe',
    language: 'french',
    accent: 'french',
    gender: 'male',
    age: 'young',
    tags: ['narration'],
    plan: PlanName.ENTREPRISE,
    previewUrl: 'https://storage.googleapis.com/eleven-public-prod/database/user/ozMB8jrBVqbaUOJusn3iJTWV1FJ3/voices/FWCNEHwbQhB1Da2r1GKI/c165f1c0-28c3-4726-8270-84be1fc4a629.mp3',
    mode: 'elevenlabs'
  },
  {
    id: '7898AMdRTtesf0Y9zS54',
    name: 'Lightsey',
    language: 'english',
    accent: 'american',
    gender: 'male',
    age: 'middle aged',
    tags: ['narration', 'audiobook', 'storytelling'],
    plan: PlanName.PRO,
    previewUrl: 'https://storage.googleapis.com/eleven-public-prod/database/user/7EAbDygyLsTi646EvIhijaFsquf1/voices/7898AMdRTtesf0Y9zS54/MqkGnRhMH2DhZRwdZc3M.mp3',
    mode: 'elevenlabs'
  },
  {
    id: 'rKTMR3hvTUh1jUArWIh4',
    name: 'Mike',
    language: 'english',
    accent: 'american',
    gender: 'male',
    age: 'middle aged',
    tags: ['narration', 'podcast'],
    plan: PlanName.PRO,
    previewUrl: 'https://storage.googleapis.com/eleven-public-prod/database/user/94k6h2pxysYlEdIuLK0DMiLix0a2/voices/rKTMR3hvTUh1jUArWIh4/a7a521f3-8725-4cab-8dfb-902449e62242.mp3',
    mode: 'elevenlabs'
  },
  {
    id: 'VCgLBmBjldJmfphyB8sZ',
    name: 'Liam',
    language: 'english',
    accent: 'american',
    gender: 'male',
    age: 'young',
    tags: ['social_media', 'storytelling'],
    plan: PlanName.PRO,
    previewUrl: 'https://storage.googleapis.com/eleven-public-prod/database/user/vVdW5WhvW0YA35KQmbv3XvRnAAg2/voices/VCgLBmBjldJmfphyB8sZ/MGNzMBHZI3BIDAE8cz38.mp3',
    mode: 'elevenlabs'
  },
  {
    id: '1cvhXKE3uxgoijz9BMLU',
    name: 'Marcus',
    language: 'english',
    accent: 'american',
    gender: 'male',
    age: 'middle aged',
    tags: ['social_media'],
    plan: PlanName.ENTREPRISE,
    previewUrl: 'https://storage.googleapis.com/eleven-public-prod/database/user/YaCZfgbNdKPjxtvOo6e847AKrkM2/voices/1cvhXKE3uxgoijz9BMLU/fb68f4e2-b114-4bc4-8620-755f7e00e751.mp3',
    mode: 'elevenlabs'
  },
  {
    id: '6MoEUz34rbRrmmyxgRm4',
    name: 'Manav',
    language: 'hindi',
    accent: 'indian',
    gender: 'male',
    age: 'young',
    tags: ['conversational'],
    plan: PlanName.PRO,
    previewUrl: 'https://storage.googleapis.com/eleven-public-prod/database/workspace/514d94e9241c48e8b7905375729c436f/voices/6MoEUz34rbRrmmyxgRm4/Y9GHbV3PIZPdGgq1nSLz.mp3',
    mode: 'elevenlabs'
  },
  {
    id: 'PukfMNJEERXCYO1uNJbI',
    name: 'Miles',
    language: 'english',
    accent: 'american',
    gender: 'male',
    age: 'young',
    tags: ['social_media'],
    plan: PlanName.ENTREPRISE,
    previewUrl: 'https://storage.googleapis.com/eleven-public-prod/database/user/dlrXfcY3xqTyGXIAqZjfLJUoUAL2/voices/PukfMNJEERXCYO1uNJbI/fXcBAKB5ddnNFuheNM4U.mp3',
    mode: 'elevenlabs'
  },
  {
    id: 'FZkK3TvQ0pjyDmT8fzIW',
    name: 'Bunty',
    language: 'hindi',
    accent: 'indian',
    gender: 'male',
    age: 'young',
    tags: ['social_media', 'storytelling'],
    plan: PlanName.PRO,
    previewUrl: 'https://storage.googleapis.com/eleven-public-prod/database/workspace/ed9b05e6324c457685490352e9a1ec90/voices/FZkK3TvQ0pjyDmT8fzIW/opgBS6JEyrQnlsYlwCAj.mp3',
    mode: 'elevenlabs'
  },
  {
    id: 'WHC0PNPIwjx2cCk34Hm8',
    name: 'Madeleine',
    language: 'german',
    accent: 'german',
    gender: 'female',
    age: 'young',
    tags: ['social_media', 'podcast', 'advertising', 'narration'],
    plan: PlanName.ENTREPRISE,
    previewUrl: 'https://storage.googleapis.com/eleven-public-prod/database/user/JkMtMybti7dSnGjkDsVqAkUgccE3/voices/WHC0PNPIwjx2cCk34Hm8/vvnYVCeh4YA8zTuebOrd.mp3',
    mode: 'elevenlabs'
  },
  {
    id: 'iKX6IXB415Hh5bn2eNhP',
    name: 'David',
    language: 'french',
    accent: 'french',
    gender: 'male',
    age: 'middle aged',
    tags: ['documentary', 'narration', 'educational'],
    plan: PlanName.PRO,
    previewUrl: 'https://storage.googleapis.com/eleven-public-prod/database/user/eFmYIzNi7fVTAUiSkCFaPtNH8aQ2/voices/iKX6IXB415Hh5bn2eNhP/w1paVoAT8XGE71VHcaAi.mp3',
    mode: 'elevenlabs'
  },
  {
    id: 'picHqyHNqhfEq8cHUtCG',
    name: 'Frederick',
    language: 'german',
    accent: 'german',
    gender: 'male',
    age: 'middle aged',
    tags: ['advertising', 'entertainment'],
    plan: PlanName.ENTREPRISE,
    previewUrl: 'https://storage.googleapis.com/eleven-public-prod/database/user/aWnKUw0pyjYMNaT9LJ1L6nH5r693/voices/picHqyHNqhfEq8cHUtCG/rCq7wjrmSgaSRm9ANnOo.mp3',
    mode: 'elevenlabs'
  },
  {
    id: 'nr2EGJNe96rzn9FRlTId',
    name: 'Yann',
    language: 'french',
    accent: 'french',
    gender: 'male',
    age: 'middle aged',
    tags: ['narration', 'podcast'],
    plan: PlanName.PRO,
    previewUrl: 'https://storage.googleapis.com/eleven-public-prod/database/user/KRHAVxDRPlRdjFaDHHWJQ0ClANE3/voices/nr2EGJNe96rzn9FRlTId/FvRYCe5PxmBMtHs8eNPV.mp3',
    mode: 'elevenlabs'
  },
  {
    id: 'cTNP6ZM2mLTKj2BFhxEh',
    name: 'Paul',
    language: 'french',
    accent: 'french',
    gender: 'male',
    age: 'middle aged',
    tags: ['podcast', 'journalism', 'documentary'],
    plan: PlanName.PRO,
    previewUrl: 'https://storage.googleapis.com/eleven-public-prod/database/user/koOonD4HAsSMVyHuP4QTaatQ9cA2/voices/cTNP6ZM2mLTKj2BFhxEh/fKLDrLD7nN8vSAKXkhzD.mp3',
    mode: 'elevenlabs'
  },
  {
    id: '9ebwxABSgElm9wISOP0J',
    name: 'Iris Romantic',
    language: 'spanish',
    accent: 'latin american',
    gender: 'female',
    age: 'young',
    tags: ['entertainment', 'narration'],
    plan: PlanName.ENTREPRISE,
    previewUrl: 'https://storage.googleapis.com/eleven-public-prod/database/user/jtTYnERxVfShx33UbofXQyQtghT2/voices/9ebwxABSgElm9wISOP0J/lPvHUX1sZYz0XxPX7Bk5.mp3',
    mode: 'elevenlabs'
  },
  {
    id: '5OnMHwgTFgvPVwE8jP6B',
    name: 'Anaïs',
    language: 'french',
    accent: 'french',
    gender: 'female',
    age: 'middle aged',
    tags: ['informative_educational', 'podcast', 'news'],
    plan: PlanName.PRO,
    previewUrl: 'https://storage.googleapis.com/eleven-public-prod/database/user/FyWpm6xUx8PZjvR3q3SsYEXjmlj1/voices/5OnMHwgTFgvPVwE8jP6B/hyOFlAxqmCLW3fVQQMAG.mp3',
    mode: 'elevenlabs'
  },
  {
    id: 'nbiTBaMRdSobTQJDzIWm',
    name: 'Antoine',
    language: 'french',
    accent: 'french',
    gender: 'male',
    age: 'middle aged',
    tags: ['informative_educational', 'narration'],
    plan: PlanName.PRO,
    previewUrl: 'https://storage.googleapis.com/eleven-public-prod/database/user/QkxEr0aPYcYgv9cCEfhUocIlVTJ3/voices/nbiTBaMRdSobTQJDzIWm/owCEge25nCYClDypQDDy.mp3',
    mode: 'elevenlabs'
  },
  {
    id: 'ViSNE020Z1wEV4uZomv5',
    name: 'Alain',
    language: 'french',
    accent: 'french',
    gender: 'male',
    age: 'middle aged',
    tags: ['narration', 'storytelling'],
    plan: PlanName.ENTREPRISE,
    previewUrl: 'https://storage.googleapis.com/eleven-public-prod/database/user/s3weMIU8KcfFYrHmAQsazlF1M1o2/voices/ViSNE020Z1wEV4uZomv5/b953bac3-d2fd-4f6d-b1e8-701e09d1c374.mp3',
    mode: 'elevenlabs'
  },
  {
    id: 'meAbY2VpJkt1q46qk56T',
    name: 'Hoda',
    language: 'arabic',
    accent: 'egyptian',
    gender: 'female',
    age: 'middle aged',
    tags: ['narration', 'conversational'],
    plan: PlanName.START,
    previewUrl: 'https://storage.googleapis.com/eleven-public-prod/database/user/k3cwQyUC1jgnRz4wTDCaJg9CSPj2/voices/meAbY2VpJkt1q46qk56T/Agu3vmW6cBTB6JmqrZKO.mp3',
    mode: 'elevenlabs'
  },
  {
    id: 'Korean_CheerfulBoyfriend',
    name: 'Minjun',
    language: 'korean',
    accent: 'korean',
    gender: 'male',
    age: 'young',
    tags: ['conversational', 'entertainment'],
    plan: PlanName.FREE,
    previewUrl: 'https://media.hoox.video/fa11acbf-9354-42d4-b2a8-030ab0ad062e.mp3',
    mode: 'minimax'
  },
  {
    id: 'Korean_GentleWoman',
    name: 'Jisoo',
    language: 'korean',
    accent: 'korean',
    gender: 'female',
    age: 'middle aged',
    tags: ['storytelling', 'narration'],
    plan: PlanName.FREE,
    previewUrl: 'https://media.hoox.video/73958e21-2892-4859-a25f-919aff0ad467.mp3',
    mode: 'minimax'
  },
  {
    id: 'Japanese_IntellectualSenior',
    name: 'Haruto',
    language: 'japanese',
    accent: 'japanese',
    gender: 'male',
    age: 'old',
    tags: ['educational', 'documentary'],
    plan: PlanName.FREE,
    previewUrl: 'https://media.hoox.video/07656ba9-43cc-4b41-bafb-805ff27b248f.mp3',
    mode: 'minimax'
  },
  {
    id: 'Japanese_KindLady',
    name: 'Yui',
    language: 'japanese',
    accent: 'japanese',
    gender: 'female',
    age: 'middle aged',
    tags: ['storytelling', 'narration'],
    plan: PlanName.FREE,
    previewUrl: 'https://media.hoox.video/006661cd-32bd-4c4c-b5fd-d1f0bf0ad924.mp3',
    mode: 'minimax'
  },
  {
    id: 'Japanese_OptimisticYouth',
    name: 'Sota',
    language: 'japanese',
    accent: 'japanese',
    gender: 'male',
    age: 'young',
    tags: ['social_media', 'entertainment'],
    plan: PlanName.FREE,
    previewUrl: 'https://media.hoox.video/0b2358f8-a996-4735-b28b-fd75bb5edd88.mp3',
    mode: 'minimax'
  },
  {
    id: 'JlPfrZoXeAKnNaogINHc',
    name: 'Matthew',
    language: 'english',
    accent: 'american',
    gender: 'male',
    age: 'middle aged',
    tags: ['conversational', 'narration'],
    plan: PlanName.ENTREPRISE,
    previewUrl: 'https://storage.googleapis.com/eleven-public-prod/database/user/Ebw6aIoLNBYbnP45ZSB5aHxmIAo2/voices/JlPfrZoXeAKnNaogINHc/KrEtDHvmgBd4TNe42CkZ.mp3',
    mode: 'elevenlabs'
  },
  {
    id: 'BNgbHR0DNeZixGQVzloa',
    name: 'David',
    language: 'english',
    accent: 'british',
    gender: 'male',
    age: 'old',
    tags: ['narration', 'storytelling'],
    plan: PlanName.PRO,
    previewUrl: 'https://storage.googleapis.com/eleven-public-prod/custom/voices/BNgbHR0DNeZixGQVzloa/40VSLvxrLAkmQgyrEA4t.mp3',
    mode: 'elevenlabs'
  },
  {
    id: 'SaqYcK3ZpDKBAImA8AdW',
    name: 'Jane',
    language: 'english',
    accent: 'american',
    gender: 'female',
    age: 'young',
    tags: ['social_media', 'narration'],
    plan: PlanName.PRO,
    previewUrl: 'https://storage.googleapis.com/eleven-public-prod/database/user/8RYUsFHsalUXjwVG0LjhNwH1j022/voices/SaqYcK3ZpDKBAImA8AdW/KOywtby6BYBzQUyFHwHK.mp3',
    mode: 'elevenlabs'
  },
  {
    id: 'Dt2jDzhoZC0pZw5bmy2S',
    name: 'Emilia',
    language: 'german',
    accent: 'german',
    gender: 'female',
    age: 'young',
    tags: ['narration'],
    plan: PlanName.START,
    previewUrl: 'https://storage.googleapis.com/eleven-public-prod/P6pUmq42X5NZv0RV97gQ0XrmuXL2/voices/Dt2jDzhoZC0pZw5bmy2S/bbed96aa-bdaf-409c-8fd4-f3af1a33447d.mp3',
    mode: 'elevenlabs'
  },
  {
    id: 'xctasy8XvGp2cVO9HL9k',
    name: 'Allison',
    language: 'english',
    accent: 'american',
    gender: 'female',
    age: 'young',
    tags: ['entertainment', 'news'],
    plan: PlanName.PRO,
    previewUrl: 'https://storage.googleapis.com/eleven-public-prod/custom/voices/xctasy8XvGp2cVO9HL9k/lsPc4Rdz6UBSdl9vu10A.mp3',
    mode: 'elevenlabs'
  },
  {
    id: 'NDeNvFOosDh4L0JoDYIq',
    name: 'José',
    language: 'spanish',
    accent: 'spanish',
    gender: 'male',
    age: 'middle aged',
    tags: ['news', 'entertainment'],
    plan: PlanName.PRO,
    previewUrl: 'https://storage.googleapis.com/eleven-public-prod/IgwDilkCraOI2af1CUCpv8HWGFt1/voices/NDeNvFOosDh4L0JoDYIq/5ed4032e-6181-49f1-975e-dedf1420303a.mp3',
    mode: 'elevenlabs'
  },
  {
    id: 'nPczCjzI2devNBz1zQrb',
    name: 'Brian',
    language: 'english',
    accent: 'american',
    gender: 'male',
    age: 'middle aged',
    tags: ['narration'],
    plan: PlanName.PRO,
    previewUrl: 'https://storage.googleapis.com/eleven-public-prod/premade/voices/nPczCjzI2devNBz1zQrb/2dd3e72c-4fd3-42f1-93ea-abc5d4e5aa1d.mp3',
    mode: 'elevenlabs'
  },
  {
    id: 'onwK4e9ZLuTAKqWW03F9',
    name: 'Daniel',
    language: 'english',
    accent: 'british',
    gender: 'male',
    age: 'middle aged',
    tags: ['news'],
    plan: PlanName.PRO,
    previewUrl: 'https://storage.googleapis.com/eleven-public-prod/premade/voices/onwK4e9ZLuTAKqWW03F9/7eee0236-1a72-4b86-b303-5dcadc007ba9.mp3',
    mode: 'elevenlabs'
  },
  {
    id: 'pFZP5JQG7iQjIQuC4Bku',
    name: 'Lily',
    language: 'english',
    accent: 'british',
    gender: 'female',
    age: 'middle aged',
    tags: ['narration'],
    plan: PlanName.PRO,
    previewUrl: 'https://storage.googleapis.com/eleven-public-prod/premade/voices/pFZP5JQG7iQjIQuC4Bku/89b68b35-b3dd-4348-a84a-a3c13a3c2b30.mp3',
    mode: 'elevenlabs'
  },
  {
    id: 'pqHfZKP75CvOlQylNhV4',
    name: 'Bill',
    language: 'english',
    accent: 'american',
    gender: 'male',
    age: 'old',
    tags: ['narration'],
    plan: PlanName.PRO,
    previewUrl: 'https://storage.googleapis.com/eleven-public-prod/premade/voices/pqHfZKP75CvOlQylNhV4/d782b3ff-84ba-4029-848c-acf01285524d.mp3',
    mode: 'elevenlabs'
  },
  {
    id: 'dY1Qa8xkWbp1fM5ny2Lo',
    name: 'Eliott',
    language: 'french',
    accent: 'french',
    gender: 'male',
    age: 'young',
    tags: ['narration'],
    plan: PlanName.PRO,
    previewUrl: 'https://storage.googleapis.com/eleven-public-prod/custom/voices/dY1Qa8xkWbp1fM5ny2Lo/Y6nHnD37GVdHFr4H0wIo.mp3',
    mode: 'elevenlabs'
  },
  {
    id: 'glDtoWIoIgk38YbycCwG',
    name: 'Clara',
    language: 'french',
    accent: 'french',
    gender: 'female',
    age: 'middle aged',
    tags: ['entertainment'],
    plan: PlanName.PRO,
    previewUrl: 'https://storage.googleapis.com/eleven-public-prod/custom/voices/glDtoWIoIgk38YbycCwG/UlDuroynnWOO94VjqAlF.mp3',
    mode: 'elevenlabs'
  },
  {
    id: 'Portuguese_CaptivatingStoryteller',
    name: 'João',
    language: 'portuguese',
    accent: 'brazilian',
    gender: 'male',
    age: 'middle aged',
    tags: ['storytelling', 'narration'],
    plan: PlanName.FREE,
    previewUrl: 'https://media.hoox.video/701666c9-ff1b-42f1-99be-ec4c4715475f.mp3',
    mode: 'minimax'
  },
  {
    id: 'Portuguese_ConfidentWoman',
    name: 'Beatriz',
    language: 'portuguese',
    accent: 'brazilian',
    gender: 'female',
    age: 'middle aged',
    tags: ['business', 'news'],
    plan: PlanName.FREE,
    previewUrl: 'https://media.hoox.video/8412d011-9497-469d-83ba-66bda1e8cddc.mp3',
    mode: 'minimax'
  },
  {
    id: 'x8FWrDHAK5xiFTJLpnHq',
    name: 'Carla',
    language: 'portuguese',
    accent: 'brazilian',
    gender: 'female',
    age: 'young',
    tags: ['social_media', 'sales'],
    plan: PlanName.ENTREPRISE,
    previewUrl: 'https://storage.googleapis.com/eleven-public-prod/database/user/k9WcK5Z5XAXJknnN0IuLUYC1r5F2/voices/x8FWrDHAK5xiFTJLpnHq/zrpZge3z9EV0l2X3Utua.mp3',
    mode: 'elevenlabs'
  },
  {
    id: 'oWAxZDx7w5VEj9dCyTzz',
    name: 'Grace',
    language: 'english',
    accent: 'american',
    gender: 'female',
    age: 'young',
    tags: ['narration'],
    plan: PlanName.PRO,
    previewUrl: 'https://storage.googleapis.com/eleven-public-prod/premade/voices/oWAxZDx7w5VEj9dCyTzz/84a36d1c-e182-41a8-8c55-dbdd15cd6e72.mp3',
    mode: 'elevenlabs'
  },
  {
    id: 'pMsXgVXv3BLzUgSXRplE',
    name: 'Serena',
    language: 'english',
    accent: 'american',
    gender: 'female',
    age: 'middle aged',
    tags: ['narration'],
    plan: PlanName.PRO,
    previewUrl: 'https://storage.googleapis.com/eleven-public-prod/premade/voices/pMsXgVXv3BLzUgSXRplE/d61f18ed-e5b0-4d0b-a33c-5c6e7e33b053.mp3',
    mode: 'elevenlabs'
  },
  {
    id: 'piTKgcLEGmPE4e6mEKli',
    name: 'Nicole',
    language: 'english',
    accent: 'american',
    gender: 'female',
    age: 'young',
    tags: ['ASMR'],
    plan: PlanName.PRO,
    previewUrl: 'https://storage.googleapis.com/eleven-public-prod/premade/voices/piTKgcLEGmPE4e6mEKli/c269a54a-e2bc-44d0-bb46-4ed2666d6340.mp3',
    mode: 'elevenlabs'
  },
  {
    id: 't0jbNlBVZ17f02VDIeMI',
    name: 'Jessie',
    language: 'english',
    accent: 'american',
    gender: 'male',
    age: 'old',
    tags: ['characters'],
    plan: PlanName.PRO,
    previewUrl: 'https://storage.googleapis.com/eleven-public-prod/premade/voices/t0jbNlBVZ17f02VDIeMI/e26939e3-61a4-4872-a41d-33922cfbdcdc.mp3',
    mode: 'elevenlabs'
  },
  {
    id: 'yoZ06aMxZJJ28mfd3POQ',
    name: 'Sam',
    language: 'english',
    accent: 'american',
    gender: 'male',
    age: 'young',
    tags: ['narration'],
    plan: PlanName.PRO,
    previewUrl: 'https://storage.googleapis.com/eleven-public-prod/premade/voices/yoZ06aMxZJJ28mfd3POQ/b017ad02-8d18-4456-ad92-55c85ecf6363.mp3',
    mode: 'elevenlabs'
  },
  {
    id: 'z9fAnlkpzviPz146aGWa',
    name: 'Glinda',
    language: 'english',
    accent: 'american',
    gender: 'female',
    age: 'middle aged',
    tags: ['characters'],
    plan: PlanName.PRO,
    previewUrl: 'https://storage.googleapis.com/eleven-public-prod/premade/voices/z9fAnlkpzviPz146aGWa/cbc60443-7b61-4ebb-b8e1-5c03237ea01d.mp3',
    mode: 'elevenlabs'
  },
  {
    id: 'zcAOhNBS3c14rBihAFp1',
    name: 'Giovanni',
    language: 'english',
    accent: 'italian',
    gender: 'male',
    age: 'young',
    tags: ['narration'],
    plan: PlanName.PRO,
    previewUrl: 'https://storage.googleapis.com/eleven-public-prod/premade/voices/zcAOhNBS3c14rBihAFp1/e7410f8f-4913-4cb8-8907-784abee5aff8.mp3',
    mode: 'elevenlabs'
  },
  {
    id: 'zrHiDhphv9ZnVXBqCLjz',
    name: 'Mimi',
    language: 'english',
    accent: 'swedish',
    gender: 'female',
    age: 'young',
    tags: ['animation', 'children_stories'],
    plan: PlanName.PRO,
    previewUrl: 'https://storage.googleapis.com/eleven-public-prod/premade/voices/zrHiDhphv9ZnVXBqCLjz/decbf20b-0f57-4fac-985b-a4f0290ebfc4.mp3',
    mode: 'elevenlabs'
  },
  {
    id: 'iP95p4xoKVk53GoZ742B',
    name: 'Chris',
    language: 'english',
    accent: 'american',
    gender: 'male',
    age: 'middle aged',
    tags: ['conversational'],
    plan: PlanName.PRO,
    previewUrl: 'https://storage.googleapis.com/eleven-public-prod/premade/voices/iP95p4xoKVk53GoZ742B/3f4bde72-cc48-40dd-829f-57fbf906f4d7.mp3',
    mode: 'elevenlabs'
  },
  {
    id: 'b6nVfb3l2zshrLZTvqbs',
    name: 'Ilona',
    language: 'french',
    accent: 'french',
    gender: 'female',
    age: 'young',
    tags: ['narration', 'social_media'],
    plan: PlanName.ENTREPRISE,
    previewUrl: 'https://storage.googleapis.com/eleven-public-prod/database/user/irKqfkQeyjUF43rcPLuZQ7UAbpn2/voices/b6nVfb3l2zshrLZTvqbs/aDmlO46A7chafGRQAEy5.mp3',
    mode: 'elevenlabs'
  },
  {
    id: 'NYC9WEgkq1u4jiqBseQ9',
    name: 'Russell',
    language: 'english',
    accent: 'british',
    gender: 'male',
    age: 'middle aged',
    tags: ['entertainment', 'news', 'documentary'],
    plan: PlanName.PRO,
    previewUrl: 'https://storage.googleapis.com/eleven-public-prod/custom/voices/NYC9WEgkq1u4jiqBseQ9/cK07157YMomRml8se448.mp3',
    mode: 'elevenlabs'
  },
  {
    id: 'Chinese (Mandarin)_News_Anchor',
    name: 'Wei',
    language: 'chinese',
    accent: 'mandarin',
    gender: 'male',
    age: 'middle aged',
    tags: ['news', 'journalism'],
    plan: PlanName.FREE,
    previewUrl: 'https://media.hoox.video/c5e45f4a-2442-4ab1-ab00-b992d20b112c.mp3',
    mode: 'minimax'
  },
  {
    id: 'Chinese (Mandarin)_Mature_Woman',
    name: 'Lin',
    language: 'chinese',
    accent: 'mandarin',
    gender: 'female',
    age: 'middle aged',
    tags: ['news', 'narration'],
    plan: PlanName.FREE,
    previewUrl: 'https://media.hoox.video/a3c8a7c9-01c7-4272-bb71-384c7fdb4b4a.mp3',
    mode: 'minimax'
  },
  {
    id: 'Chinese (Mandarin)_Warm_Girl',
    name: 'Mei',
    language: 'chinese',
    accent: 'mandarin',
    gender: 'female',
    age: 'young',
    tags: ['social_media', 'conversational'],
    plan: PlanName.FREE,
    previewUrl: 'https://media.hoox.video/8c6894de-c7a0-4c2c-bcee-710a3fda97fb.mp3',
    mode: 'minimax'
  },
]

export const accentFlags: Record<string, string> = {
  'french': '🇫🇷',
  'canadian': '🇨🇦',
  'spanish': '🇪🇸',
  'japanese': '🇯🇵',
  'english': '🇬🇧',
  'american': '🇺🇸',
  'british': '🇬🇧',
  'australian': '🇦🇺',
  'irish': '🇮🇪',
  'german': '🇩🇪',
  'swedish': '🇸🇪',
  'croatian': '🇭🇷',
  'nigerian': '🇳🇬',
  'indian': '🇮🇳',
  'italian': '🇮🇹',
  'latin american': '🇲🇽',
  'egyptian': '🇪🇬',
  'arabic': '🇸🇦',
  'peninsular': '🇪🇸',
  'brazilian': '🇧🇷',
  'korean': '🇰🇷',
  'mandarin': '🇨🇳',
}