import Link from "next/link";
import { Button } from "@/src/components/ui/button";
import { ArrowLeft } from "lucide-react";

const PrivacyPolicy = () => {
  return (
    <main className="max-w-xl mx-auto">
      <div className="p-5">
        <Button variant="link" asChild>
          <Link href="/">
            <ArrowLeft className="w-4 h-4 mr-2" />
            Back
          </Link>
        </Button>
        <h1 className="text-3xl font-extrabold pb-6">
          Privacy Policy for Hoox
        </h1>

        <pre
          className="leading-relaxed whitespace-pre-wrap"
          style={{ fontFamily: "sans-serif" }}
        >
          {`PRIVACY POLICY

Last Updated: December 14, 2023

1. INTRODUCTION

Welcome to Hoox ("we," "our," or "us"). This Privacy Policy explains how we collect, use, disclose, and safeguard your information when you visit our website https://hoox.video and use our AI video generation services.

2. INFORMATION WE COLLECT

2.1 Personal Data
- Name
- Email address
- Payment information

2.2 Non-Personal Data
- Browser cookies
- Usage data
- Technical information

3. HOW WE USE YOUR INFORMATION

We use the collected information for:
- Processing your orders
- Managing your account
- Providing customer support
- Sending service updates
- Improving our services

4. DATA STORAGE AND SECURITY

We implement appropriate security measures to protect your personal information. Your data is stored securely and accessed only by authorized personnel.

5. COOKIES

We use cookies to enhance your browsing experience. You can control cookie settings through your browser preferences.

6. DATA SHARING

We do not share, sell, rent, or trade your personal information with third parties. We may disclose your information if required by law or to protect our rights.

7. USER-GENERATED CONTENT

All content generated by users through our platform belongs exclusively to the respective users. However, Hoox assumes no responsibility for user-generated content and its use. Users are solely responsible for ensuring their generated content complies with applicable laws and regulations. Hoox reserves the right to remove any content that violates our terms of service or applicable laws.

8. CHILDREN'S PRIVACY

We do not knowingly collect or maintain information from persons under 13 years of age. If we learn that personal information of persons under 13 has been collected, we will take appropriate steps to delete this information.

9. CHANGES TO THIS PRIVACY POLICY

We may update this Privacy Policy from time to time. We will notify you of any changes by sending an email to the address you have provided and/or by posting the new Privacy Policy on this page.

10. YOUR RIGHTS

You have the right to:
- Access your personal data
- Correct inaccurate data
- Request deletion of your data
- Withdraw consent
- Export your data

11. CONTACT US

If you have questions about this Privacy Policy, please contact us at:
Email: contact@hoox.video

12. GOVERNING LAW

This Privacy Policy is governed by and construed in accordance with applicable laws. Any disputes relating to this policy will be subject to the exclusive jurisdiction of the courts where our company is registered.`}
        </pre>
      </div>
    </main>
  );
};

export default PrivacyPolicy;
